import type { RawQuestion } from "./bank-types";

export const MATHS_QUESTIONS: Record<string, RawQuestion[]> = {
  "m9-coordinates": [
    ["easy", "The point (−3, 4) lies in which quadrant?", "Second quadrant", ["First quadrant", "Third quadrant", "Fourth quadrant"], "x is negative and y is positive in Quadrant II."],
    ["easy", "The coordinates of the origin are:", "(0, 0)", ["(1, 1)", "(0, 1)", "(1, 0)"], "The axes cross at the origin."],
    ["medium", "A point on the y-axis always has:", "x-coordinate 0", ["y-coordinate 0", "Both coordinates equal", "Both coordinates negative"], "Points on the y-axis are of the form (0, y)."],
    ["medium", "The distance of the point (5, −7) from the x-axis is:", "7 units", ["5 units", "12 units", "2 units"], "Distance from the x-axis equals |y| = 7."],
    ["hard", "The distance between (2, 3) and (2, −5) is:", "8 units", ["2 units", "5 units", "√68 units"], "Same x, so distance = |3 − (−5)| = 8."],
  ],
  "m9-linear-poly": [
    ["easy", "The degree of the polynomial 7x + 2 is:", "1", ["0", "2", "7"], "The highest power of x is 1, so it is linear."],
    ["easy", "The zero of p(x) = x − 4 is:", "4", ["−4", "0", "1"], "p(4) = 4 − 4 = 0."],
    ["medium", "The zero of p(x) = 2x + 6 is:", "−3", ["3", "6", "−6"], "2x + 6 = 0 gives x = −3."],
    ["medium", "If p(x) = 3x − 2, then p(2) is:", "4", ["1", "6", "−4"], "3 × 2 − 2 = 4."],
    ["hard", "The graph of y = 2x + 1 is a straight line that crosses the y-axis at:", "(0, 1)", ["(1, 0)", "(0, 2)", "(−½, 1)"], "Put x = 0: y = 1."],
  ],
  "m9-numbers": [
    ["easy", "Which of these is irrational?", "√2", ["0.25", "3/7", "√9"], "√2 cannot be written as p/q; √9 = 3 is rational."],
    ["easy", "Every rational number has a decimal expansion that is:", "Terminating or non-terminating repeating", ["Always terminating", "Non-terminating non-repeating", "Always an integer"], "Non-terminating non-repeating decimals are irrational."],
    ["medium", "0.333… written as a fraction is:", "1/3", ["3/10", "33/100", "3/9 × 10"], "Let x = 0.333…; 10x − x = 3, so x = 1/3."],
    ["medium", "The value of 8^(2/3) is:", "4", ["2", "16", "64/3"], "8^(1/3) = 2, and 2² = 4."],
    ["hard", "Rationalising 1/(√3 + √2) gives:", "√3 − √2", ["√3 + √2", "1/(√3 − √2)", "√6"], "Multiply by (√3 − √2): denominator becomes 3 − 2 = 1."],
  ],
  "m9-identities": [
    ["easy", "(a + b)² equals:", "a² + 2ab + b²", ["a² + b²", "a² − 2ab + b²", "2a + 2b"], "This is the standard identity for the square of a sum."],
    ["easy", "a² − b² equals:", "(a + b)(a − b)", ["(a − b)²", "(a + b)²", "a(a − b)"], "Difference of squares identity."],
    ["medium", "Using an identity, 103 × 97 equals:", "9991", ["9999", "10009", "9900"], "(100 + 3)(100 − 3) = 10000 − 9 = 9991."],
    ["medium", "Factorise x² − 6x + 9:", "(x − 3)²", ["(x + 3)²", "(x − 3)(x + 3)", "(x − 9)(x + 1)"], "It matches a² − 2ab + b² with a = x, b = 3."],
    ["hard", "If a + b + c = 0, then a³ + b³ + c³ equals:", "3abc", ["0", "abc", "a + b + c"], "a³ + b³ + c³ − 3abc = (a + b + c)(…) = 0."],
  ],
  "m9-circles": [
    ["easy", "The longest chord of a circle is the:", "Diameter", ["Radius", "Arc", "Tangent"], "A diameter passes through the centre."],
    ["easy", "A diameter is how many times the radius?", "2", ["½", "π", "4"], "d = 2r."],
    ["medium", "The perpendicular from the centre of a circle to a chord:", "Bisects the chord", ["Is always equal to the radius", "Doubles the chord", "Is parallel to the chord"], "It divides the chord into two equal parts."],
    ["medium", "Equal chords of a circle subtend angles at the centre that are:", "Equal", ["Supplementary", "Complementary", "Right angles"], "Equal chords subtend equal angles at the centre."],
    ["hard", "A chord of length 8 cm is 3 cm from the centre. The radius is:", "5 cm", ["4 cm", "7 cm", "√55 cm"], "Half-chord 4 and distance 3 give r = √(16 + 9) = 5 cm."],
  ],
  "m9-area": [
    ["easy", "The circumference of a circle of radius r is:", "2πr", ["πr²", "πr", "4πr"], "Circumference = 2πr = πd."],
    ["easy", "The perimeter of a square of side 6 cm is:", "24 cm", ["36 cm", "12 cm", "18 cm"], "4 × 6 = 24 cm."],
    ["medium", "Heron's formula for a triangle with semi-perimeter s is:", "√[s(s − a)(s − b)(s − c)]", ["½ × base × height", "s(a + b + c)", "√(a² + b² + c²)"], "It finds area using only the three side lengths."],
    ["medium", "Using Heron's formula, the area of a triangle with sides 3, 4 and 5 cm is:", "6 cm²", ["12 cm²", "7.5 cm²", "10 cm²"], "s = 6, area = √(6 × 3 × 2 × 1) = 6 cm²."],
    ["hard", "The length of an arc of angle 90° in a circle of radius 14 cm (π = 22/7) is:", "22 cm", ["44 cm", "11 cm", "88 cm"], "(90/360) × 2 × (22/7) × 14 = 22 cm."],
  ],
  "m9-probability": [
    ["easy", "The probability of any event lies between:", "0 and 1 (inclusive)", ["−1 and 1", "1 and 10", "0 and 100 only"], "0 means impossible and 1 means certain."],
    ["easy", "A coin is tossed 50 times and shows heads 28 times. The experimental probability of heads is:", "0.56", ["0.5", "0.28", "0.44"], "28/50 = 0.56."],
    ["medium", "In 200 trials an event happened 50 times. Its experimental probability is:", "0.25", ["0.5", "0.4", "4"], "50/200 = 0.25."],
    ["hard", "If the experimental probability of rain on a day is 0.3, the probability of no rain is:", "0.7", ["0.3", "1.3", "0"], "The two outcomes add up to 1."],
  ],
  "m9-sequences": [
    ["easy", "The next term of 3, 7, 11, 15, … is:", "19", ["18", "20", "21"], "The common difference is 4."],
    ["easy", "In the sequence 2, 4, 8, 16, … each term is:", "Double the previous term", ["4 more than the previous", "Half the previous", "Squared each time"], "Multiply by 2 each time."],
    ["medium", "The general term of 5, 8, 11, 14, … is:", "3n + 2", ["5n", "n + 3", "3n − 2"], "First term 5 and difference 3: 5 + 3(n − 1) = 3n + 2."],
    ["hard", "The 10th term of the sequence 1, 4, 9, 16, … is:", "100", ["81", "40", "121"], "The nth term is n², so the 10th term is 100."],
  ],

  "m10-real": [
    ["easy", "The HCF of 12 and 18 is:", "6", ["36", "3", "2"], "12 = 2² × 3 and 18 = 2 × 3²; common factors give 2 × 3 = 6."],
    ["easy", "The Fundamental Theorem of Arithmetic says every composite number can be written:", "Uniquely as a product of primes", ["As a sum of two primes", "As a square", "As a rational number"], "The prime factorisation is unique apart from order."],
    ["medium", "If HCF(a, b) = 4 and a × b = 96, then LCM(a, b) is:", "24", ["384", "12", "100"], "HCF × LCM = a × b, so LCM = 96/4 = 24."],
    ["medium", "The LCM of 6 and 20 is:", "60", ["120", "2", "30"], "6 = 2 × 3, 20 = 2² × 5; LCM = 2² × 3 × 5 = 60."],
    ["hard", "Which of these is irrational?", "3 + 2√5", ["√16", "22/7", "0.121212…"], "Sum of a rational and a non-zero irrational is irrational."],
  ],
  "m10-poly": [
    ["easy", "The zeros of x² − 5x + 6 are:", "2 and 3", ["−2 and −3", "1 and 6", "5 and 6"], "x² − 5x + 6 = (x − 2)(x − 3)."],
    ["easy", "A quadratic polynomial can have at most how many zeros?", "2", ["1", "3", "Infinitely many"], "Number of zeros ≤ degree."],
    ["medium", "For ax² + bx + c, the sum of zeros is:", "−b/a", ["b/a", "c/a", "−c/a"], "α + β = −b/a and αβ = c/a."],
    ["hard", "A quadratic polynomial whose zeros have sum 4 and product 3 is:", "x² − 4x + 3", ["x² + 4x + 3", "x² − 3x + 4", "x² + 3x − 4"], "x² − (sum)x + product."],
  ],
  "m10-linear": [
    ["easy", "The solution of x + y = 5 and x − y = 1 is:", "x = 3, y = 2", ["x = 2, y = 3", "x = 4, y = 1", "x = 5, y = 0"], "Adding gives 2x = 6, so x = 3 and y = 2."],
    ["medium", "Two lines with a₁/a₂ ≠ b₁/b₂ are:", "Intersecting (unique solution)", ["Parallel", "Coincident", "Never consistent"], "Different slopes mean the lines meet at exactly one point."],
    ["medium", "The pair 2x + 3y = 5 and 4x + 6y = 10 has:", "Infinitely many solutions", ["No solution", "A unique solution", "Exactly two solutions"], "All ratios are equal (1/2), so the lines coincide."],
    ["hard", "For what k do kx + 2y = 5 and 3x + y = 1 have no solution?", "k = 6", ["k = 3", "k = 2", "k = 5"], "Need k/3 = 2/1 ≠ 5/1, so k = 6."],
  ],
  "m10-quadratic": [
    ["easy", "Which is a quadratic equation?", "x² − 3x + 2 = 0", ["x³ + 1 = 0", "2x + 5 = 0", "1/x = 4"], "Highest power of x is 2."],
    ["medium", "The roots of x² − 9 = 0 are:", "3 and −3", ["9 and −9", "3 only", "0 and 9"], "x² = 9 gives x = ±3."],
    ["medium", "The discriminant of 2x² + 3x + 1 = 0 is:", "1", ["17", "−1", "9"], "D = b² − 4ac = 9 − 8 = 1."],
    ["hard", "If the discriminant of a quadratic is negative, its roots are:", "Not real", ["Real and equal", "Real and distinct", "Both zero"], "D < 0 means no real roots."],
  ],
  "m10-ap": [
    ["easy", "The common difference of 7, 11, 15, 19, … is:", "4", ["7", "3", "11"], "11 − 7 = 4."],
    ["medium", "The 10th term of the AP 2, 5, 8, … is:", "29", ["32", "30", "27"], "a₁₀ = 2 + 9 × 3 = 29."],
    ["medium", "The sum of the first 10 natural numbers is:", "55", ["50", "100", "45"], "n(n + 1)/2 = 10 × 11/2 = 55."],
    ["hard", "The sum of the first 20 terms of 1, 3, 5, … is:", "400", ["200", "380", "420"], "Sₙ = n² for odd numbers: 20² = 400."],
  ],
  "m10-coord": [
    ["easy", "The distance between (0, 0) and (3, 4) is:", "5", ["7", "1", "25"], "√(3² + 4²) = 5."],
    ["easy", "The midpoint of (2, 4) and (6, 8) is:", "(4, 6)", ["(8, 12)", "(3, 4)", "(2, 2)"], "((2 + 6)/2, (4 + 8)/2) = (4, 6)."],
    ["medium", "The point dividing (1, 2) and (7, 8) in the ratio 1 : 2 is:", "(3, 4)", ["(5, 6)", "(4, 5)", "(2, 3)"], "x = (1×7 + 2×1)/3 = 3, y = (1×8 + 2×2)/3 = 4."],
    ["hard", "The distance of (−6, 8) from the origin is:", "10", ["14", "2", "100"], "√(36 + 64) = 10."],
  ],
  "m10-triangles": [
    ["easy", "All congruent figures are also:", "Similar", ["Unequal", "Never similar", "Right-angled"], "Congruent = similar with ratio 1."],
    ["medium", "The Basic Proportionality Theorem is also called:", "Thales' theorem", ["Pythagoras' theorem", "Euclid's lemma", "Heron's theorem"], "A line parallel to one side divides the other two sides in the same ratio."],
    ["medium", "In △ABC, DE ∥ BC with AD = 2, DB = 3 and AE = 4. Then EC is:", "6", ["5", "8", "1.5"], "AD/DB = AE/EC gives 2/3 = 4/EC, so EC = 6."],
    ["hard", "Two triangles with corresponding angles equal are similar by the:", "AA criterion", ["SSS congruence", "RHS congruence", "SAS congruence"], "Two equal angle pairs are enough for similarity."],
  ],
  "m10-circles": [
    ["easy", "A tangent to a circle touches it at:", "Exactly one point", ["Two points", "No point", "Three points"], "A secant cuts the circle at two points."],
    ["medium", "The angle between a tangent and the radius at the point of contact is:", "90°", ["45°", "60°", "180°"], "The tangent is perpendicular to the radius."],
    ["medium", "From an external point, how many tangents can be drawn to a circle?", "2", ["1", "0", "Infinitely many"], "Exactly two tangents, and they are equal in length."],
    ["hard", "A tangent from a point 13 cm from the centre of a circle of radius 5 cm has length:", "12 cm", ["8 cm", "18 cm", "√194 cm"], "√(13² − 5²) = √144 = 12 cm."],
  ],
  "m10-trig": [
    ["easy", "sin 30° equals:", "1/2", ["√3/2", "1", "1/√2"], "Standard value."],
    ["easy", "tan θ equals:", "sin θ / cos θ", ["cos θ / sin θ", "1 / sin θ", "sin θ × cos θ"], "tan = opposite/adjacent = sin/cos."],
    ["medium", "sin²θ + cos²θ equals:", "1", ["0", "2", "tan²θ"], "Fundamental identity."],
    ["hard", "If tan A = 3/4 (A acute), then sin A is:", "3/5", ["4/5", "3/4", "5/3"], "Sides 3, 4, hypotenuse 5, so sin A = 3/5."],
  ],
  "m10-heights": [
    ["easy", "The angle between the line of sight and the horizontal when looking up at an object is the:", "Angle of elevation", ["Angle of depression", "Right angle", "Reflex angle"], "Looking down gives the angle of depression."],
    ["medium", "A tower casts a shadow equal to its height. The Sun's elevation is:", "45°", ["30°", "60°", "90°"], "tan θ = height/shadow = 1, so θ = 45°."],
    ["medium", "From 30 m away, the top of a tower is seen at 60°. The height of the tower is:", "30√3 m", ["10√3 m", "15 m", "60 m"], "h = 30 × tan 60° = 30√3 m."],
    ["hard", "A 10 m ladder makes 60° with the ground. The height it reaches on the wall is:", "5√3 m", ["5 m", "10√3 m", "20 m"], "h = 10 × sin 60° = 5√3 m."],
  ],
  "m10-areas": [
    ["easy", "The area of a sector of angle θ in a circle of radius r is:", "(θ/360°) × πr²", ["(θ/360°) × 2πr", "θ × r", "πr²/θ"], "It is a fraction of the full circle's area."],
    ["medium", "The area of a quadrant of a circle of radius 14 cm (π = 22/7) is:", "154 cm²", ["616 cm²", "44 cm²", "308 cm²"], "¼ × (22/7) × 14 × 14 = 154 cm²."],
    ["medium", "The length of an arc of 60° in a circle of radius 21 cm (π = 22/7) is:", "22 cm", ["44 cm", "66 cm", "11 cm"], "(60/360) × 2 × (22/7) × 21 = 22 cm."],
    ["hard", "The area of a minor segment equals:", "Area of the sector − area of the triangle", ["Area of the sector + area of the triangle", "Area of the circle − area of the sector", "Length of the arc × radius"], "Remove the triangle from the sector."],
  ],
  "m10-surface": [
    ["easy", "The volume of a cylinder is:", "πr²h", ["2πrh", "⅓πr²h", "4/3πr³"], "Base area × height."],
    ["medium", "The volume of a sphere of radius r is:", "4/3 πr³", ["4πr²", "2/3 πr³", "πr²h"], "4πr² is its surface area."],
    ["medium", "A toy is a cone on a hemisphere of the same radius. Its total volume is:", "Volume of cone + volume of hemisphere", ["Volume of cone − volume of hemisphere", "Surface area of the cone", "Volume of a full sphere"], "Combined solids add their volumes."],
    ["hard", "The curved surface area of a hemisphere of radius 7 cm (π = 22/7) is:", "308 cm²", ["154 cm²", "462 cm²", "616 cm²"], "2πr² = 2 × (22/7) × 49 = 308 cm²."],
  ],
  "m10-stats": [
    ["easy", "The most frequently occurring value in a data set is the:", "Mode", ["Mean", "Median", "Range"], "Mode = highest frequency."],
    ["medium", "The class mark of the class 10–20 is:", "15", ["10", "20", "30"], "(10 + 20)/2 = 15."],
    ["medium", "The empirical relation between mean, median and mode is:", "3 Median = Mode + 2 Mean", ["Mode = Mean + Median", "Mean = 3 Mode − 2 Median", "Median = Mean × Mode"], "Used to estimate one measure from the other two."],
    ["hard", "In the median formula for grouped data, 'cf' stands for the:", "Cumulative frequency of the class before the median class", ["Frequency of the median class", "Class width", "Total frequency"], "Median = l + [(n/2 − cf)/f] × h."],
  ],
  "m10-prob": [
    ["easy", "The probability of getting a head when a fair coin is tossed is:", "1/2", ["1", "0", "1/4"], "Two equally likely outcomes, one favourable."],
    ["easy", "The probability of an impossible event is:", "0", ["1", "1/2", "−1"], "It can never happen."],
    ["medium", "A die is thrown. The probability of an even number is:", "1/2", ["1/3", "1/6", "2/3"], "Even outcomes: 2, 4, 6 → 3/6."],
    ["medium", "If P(E) = 0.35, then P(not E) is:", "0.65", ["0.35", "1.35", "0"], "P(E) + P(not E) = 1."],
    ["hard", "A card is drawn from a well-shuffled deck of 52. The probability that it is a king is:", "1/13", ["1/52", "4/13", "1/4"], "4 kings out of 52 cards."],
  ],
};

export const MATHS_CARDS: Record<string, [string, string][]> = {
  "m9-coordinates": [["Abscissa", "The x-coordinate of a point"], ["Ordinate", "The y-coordinate of a point"], ["Quadrant II signs", "(−, +)"], ["Origin", "(0, 0)"]],
  "m9-linear-poly": [["Linear polynomial", "Degree 1, e.g., ax + b"], ["Zero of ax + b", "x = −b/a"], ["Constant polynomial", "Degree 0"], ["Graph of linear relation", "A straight line"]],
  "m9-numbers": [["Rational number", "Can be written as p/q, q ≠ 0"], ["Irrational number", "Non-terminating, non-repeating decimal"], ["aᵐ × aⁿ", "aᵐ⁺ⁿ"], ["Rationalising", "Removing a surd from the denominator"]],
  "m9-identities": [["(a − b)²", "a² − 2ab + b²"], ["(a + b)³", "a³ + b³ + 3ab(a + b)"], ["a³ + b³", "(a + b)(a² − ab + b²)"], ["(a + b + c)²", "a² + b² + c² + 2ab + 2bc + 2ca"]],
  "m9-circles": [["Chord", "Line segment joining two points on a circle"], ["Diameter", "Longest chord, 2r"], ["Arc", "Part of the circumference"], ["Perpendicular from centre", "Bisects the chord"]],
  "m9-area": [["Circumference", "2πr"], ["Heron's formula", "√[s(s−a)(s−b)(s−c)]"], ["Semi-perimeter", "s = (a + b + c)/2"], ["Arc length", "(θ/360) × 2πr"]],
  "m9-probability": [["Experimental probability", "Times event occurred ÷ total trials"], ["Range of probability", "0 to 1"], ["Certain event", "Probability 1"], ["Impossible event", "Probability 0"]],
  "m9-sequences": [["Arithmetic sequence", "Constant difference between terms"], ["Common difference", "d = a₂ − a₁"], ["General term", "Formula for the nth term"], ["Square numbers", "1, 4, 9, 16, …"]],
  "m10-real": [["HCF × LCM", "Product of the two numbers"], ["Fundamental Theorem of Arithmetic", "Unique prime factorisation"], ["√2", "Irrational"], ["Co-prime", "HCF is 1"]],
  "m10-poly": [["Sum of zeros", "−b/a"], ["Product of zeros", "c/a"], ["Quadratic from zeros", "x² − (sum)x + product"], ["Max zeros of cubic", "3"]],
  "m10-linear": [["Unique solution", "a₁/a₂ ≠ b₁/b₂"], ["No solution", "a₁/a₂ = b₁/b₂ ≠ c₁/c₂"], ["Infinite solutions", "All three ratios equal"], ["Elimination", "Add/subtract to remove a variable"]],
  "m10-quadratic": [["Quadratic formula", "x = [−b ± √(b² − 4ac)]/2a"], ["Discriminant", "D = b² − 4ac"], ["D = 0", "Real and equal roots"], ["D < 0", "No real roots"]],
  "m10-ap": [["nth term", "aₙ = a + (n − 1)d"], ["Sum of n terms", "Sₙ = n/2 [2a + (n − 1)d]"], ["Sum with last term", "Sₙ = n/2 (a + l)"], ["Sum of first n naturals", "n(n + 1)/2"]],
  "m10-coord": [["Distance formula", "√[(x₂ − x₁)² + (y₂ − y₁)²]"], ["Midpoint", "((x₁ + x₂)/2, (y₁ + y₂)/2)"], ["Section formula", "((mx₂ + nx₁)/(m + n), (my₂ + ny₁)/(m + n))"], ["Distance from origin", "√(x² + y²)"]],
  "m10-triangles": [["Similar triangles", "Same shape, proportional sides"], ["BPT", "Line ∥ to one side divides the others proportionally"], ["AA criterion", "Two equal angles ⇒ similar"], ["SSS similarity", "All sides in the same ratio"]],
  "m10-circles": [["Tangent", "Touches the circle at one point"], ["Tangent ⟂ radius", "At the point of contact"], ["Tangents from a point", "Equal in length"], ["Secant", "Line cutting a circle at two points"]],
  "m10-trig": [["sin θ", "Opposite / hypotenuse"], ["cos 60°", "1/2"], ["tan 45°", "1"], ["1 + tan²θ", "sec²θ"]],
  "m10-heights": [["Angle of elevation", "Looking up from the horizontal"], ["Angle of depression", "Looking down from the horizontal"], ["tan 60°", "√3"], ["tan 30°", "1/√3"]],
  "m10-areas": [["Sector area", "(θ/360) × πr²"], ["Arc length", "(θ/360) × 2πr"], ["Segment", "Sector minus triangle"], ["Quadrant", "Sector with θ = 90°"]],
  "m10-surface": [["Cone volume", "⅓πr²h"], ["Sphere surface area", "4πr²"], ["Hemisphere CSA", "2πr²"], ["Cylinder CSA", "2πrh"]],
  "m10-stats": [["Class mark", "(Upper + lower limit)/2"], ["Mode formula", "l + [(f₁ − f₀)/(2f₁ − f₀ − f₂)] × h"], ["Median formula", "l + [(n/2 − cf)/f] × h"], ["Empirical relation", "3 Median = Mode + 2 Mean"]],
  "m10-prob": [["P(E)", "Favourable outcomes ÷ total outcomes"], ["P(not E)", "1 − P(E)"], ["Sure event", "Probability 1"], ["Deck of cards", "52 cards, 4 suits, 13 each"]],
};
