import type { RawQuestion } from "./bank-types";

export const SCIENCE_QUESTIONS: Record<string, RawQuestion[]> = {
  "s9-exploration": [
    ["easy", "Which step usually comes right after making an observation in the scientific method?", "Asking a question and forming a hypothesis", ["Publishing the result", "Drawing the final conclusion", "Ignoring unexpected data"], "Inquiry starts with an observation, which leads to a question and a testable hypothesis."],
    ["easy", "In a fair test, how many variables should you deliberately change at a time?", "Only one (the independent variable)", ["All of them", "Two at the same time", "None"], "Changing one variable while keeping the others controlled lets you link cause and effect."],
    ["medium", "A student sees wet ground and says 'it rained at night'. This statement is an:", "Inference", ["Observation", "Law", "Measurement"], "Seeing wet ground is the observation; explaining why it is wet is an inference."],
    ["medium", "A good scientific hypothesis must be:", "Testable and falsifiable", ["Always proven true", "Based only on opinion", "Impossible to test"], "Science only works with ideas that experiments or observations can support or reject."],
    ["hard", "Plants are grown with different amounts of light while water and soil are kept the same. The plant height measured is the:", "Dependent variable", ["Independent variable", "Controlled variable", "Hypothesis"], "The outcome you measure depends on the factor you change (light), so height is dependent."],
  ],
  "s9-cell": [
    ["easy", "Who first observed and named 'cells' in a slice of cork (1665)?", "Robert Hooke", ["Robert Brown", "Leeuwenhoek", "Schleiden"], "Hooke saw box-like compartments in cork and called them cells."],
    ["easy", "Which organelle is called the 'powerhouse of the cell'?", "Mitochondria", ["Ribosome", "Golgi apparatus", "Lysosome"], "Mitochondria release energy from food as ATP during cellular respiration."],
    ["medium", "Which of these is present in plant cells but absent in animal cells?", "Cell wall made of cellulose", ["Plasma membrane", "Nucleus", "Mitochondria"], "Plant cells have a rigid cellulose cell wall outside the plasma membrane."],
    ["medium", "A raisin placed in water swells up. This happens due to:", "Endosmosis", ["Exosmosis", "Plasmolysis", "Active transport"], "Water moves into the raisin from a region of higher water concentration through a membrane."],
    ["hard", "Which type of cell division produces four cells with half the chromosome number?", "Meiosis", ["Mitosis", "Binary fission", "Budding"], "Meiosis halves the chromosome number to form gametes; mitosis keeps it the same."],
    ["hard", "Prokaryotic cells differ from eukaryotic cells because they lack:", "A membrane-bound nucleus", ["Ribosomes", "Cytoplasm", "A plasma membrane"], "Prokaryotes (like bacteria) have a nucleoid region without a nuclear membrane."],
  ],
  "s9-tissues": [
    ["easy", "Which plant tissue is responsible for growth at root and shoot tips?", "Apical meristem", ["Xylem", "Parenchyma", "Cork"], "Apical meristem cells divide actively to increase length."],
    ["easy", "Which tissue transports water and minerals in plants?", "Xylem", ["Phloem", "Epidermis", "Collenchyma"], "Xylem carries water upward from roots; phloem carries food."],
    ["medium", "Tendons connect:", "Muscle to bone", ["Bone to bone", "Muscle to muscle", "Skin to muscle"], "Tendons are tough connective tissue joining muscles to bones; ligaments join bone to bone."],
    ["medium", "Which muscle type is involuntary and found in the walls of the stomach and intestine?", "Smooth (unstriated) muscle", ["Skeletal muscle", "Cardiac muscle only", "Voluntary muscle"], "Smooth muscle works without conscious control in internal organs."],
    ["hard", "A ball-and-socket joint is found at the:", "Shoulder", ["Knee", "Elbow", "Skull sutures"], "The shoulder and hip allow rotation in many directions; knee and elbow are hinge joints."],
  ],
  "s9-motion": [
    ["easy", "An athlete runs one full lap of a circular track and returns to the start. The displacement is:", "Zero", ["Equal to the circumference", "Twice the radius", "Equal to the radius"], "Displacement is the shortest distance between start and end points, which coincide here."],
    ["easy", "The SI unit of acceleration is:", "m/s²", ["m/s", "m", "N"], "Acceleration is change in velocity per second: (m/s)/s."],
    ["medium", "The slope of a velocity–time graph gives:", "Acceleration", ["Distance", "Displacement", "Speed only"], "Slope = change in velocity ÷ time = acceleration."],
    ["medium", "A car starts from rest and reaches 20 m/s in 5 s. Its acceleration is:", "4 m/s²", ["100 m/s²", "0.25 m/s²", "25 m/s²"], "a = (v − u)/t = (20 − 0)/5 = 4 m/s²."],
    ["hard", "The area under a velocity–time graph represents:", "Displacement", ["Acceleration", "Force", "Speed"], "Area = velocity × time = displacement."],
    ["hard", "Uniform circular motion is accelerated motion because:", "The direction of velocity keeps changing", ["Speed keeps increasing", "Distance stays zero", "No force acts on the body"], "Velocity is a vector; a change in direction alone means acceleration."],
  ],
  "s9-mixtures": [
    ["easy", "Which of these is a homogeneous mixture?", "Salt dissolved in water", ["Sand in water", "Oil in water", "Chalk in water"], "A true solution has uniform composition throughout."],
    ["easy", "Which method separates the coloured components of ink?", "Chromatography", ["Filtration", "Sublimation", "Decantation"], "Different dyes travel at different speeds on the paper."],
    ["medium", "Milk is an example of a:", "Colloid", ["True solution", "Suspension", "Pure substance"], "Milk has fat particles dispersed in water that do not settle and scatter light."],
    ["medium", "The scattering of a beam of light by colloidal particles is called the:", "Tyndall effect", ["Brownian motion", "Dispersion", "Refraction"], "Colloidal particles are large enough to scatter light, making the beam visible."],
    ["hard", "40 g of salt is dissolved in 360 g of water. The mass percentage of the solution is:", "10%", ["11.1%", "40%", "9%"], "Mass % = solute/(solute + solvent) × 100 = 40/400 × 100 = 10%."],
    ["hard", "Ammonium chloride can be separated from common salt by:", "Sublimation", ["Distillation", "Chromatography", "Filtration"], "Ammonium chloride changes directly from solid to vapour on heating; salt does not."],
  ],
  "s9-forces": [
    ["easy", "Newton's first law is also called the law of:", "Inertia", ["Acceleration", "Action and reaction", "Gravitation"], "A body stays at rest or in uniform motion unless an unbalanced force acts."],
    ["easy", "The SI unit of force is the:", "Newton", ["Joule", "Watt", "Pascal"], "1 N = 1 kg·m/s²."],
    ["medium", "A 2 kg mass accelerates at 3 m/s². The net force on it is:", "6 N", ["1.5 N", "5 N", "0.67 N"], "F = ma = 2 × 3 = 6 N."],
    ["medium", "When you jump off a boat onto the shore, the boat moves backward. This is explained by:", "Newton's third law", ["Newton's first law", "Law of conservation of mass", "Archimedes' principle"], "Your push on the boat produces an equal and opposite push of the boat."],
    ["hard", "Passengers lurch forward when a moving bus brakes suddenly because of:", "Inertia of motion", ["Inertia of rest", "Friction of the seat", "Gravity"], "Their bodies tend to keep moving forward while the bus stops."],
  ],
  "s9-work": [
    ["easy", "Work is done when:", "A force moves an object in the direction of the force", ["A force is applied but nothing moves", "An object is at rest", "Only heat is produced"], "W = F × s requires displacement along the force."],
    ["easy", "Energy possessed by a body due to its motion is:", "Kinetic energy", ["Potential energy", "Chemical energy", "Nuclear energy"], "KE = ½mv²."],
    ["medium", "A 10 kg object is raised to 5 m (g = 10 m/s²). Its potential energy is:", "500 J", ["50 J", "250 J", "5000 J"], "PE = mgh = 10 × 10 × 5 = 500 J."],
    ["medium", "If the speed of a body doubles, its kinetic energy becomes:", "Four times", ["Twice", "Half", "Unchanged"], "KE depends on v², so doubling v multiplies KE by 4."],
    ["hard", "A machine lifts a 200 N load using a 50 N effort. Its mechanical advantage is:", "4", ["0.25", "150", "250"], "MA = load ÷ effort = 200/50 = 4."],
    ["hard", "A 60 W bulb glows for 10 s. The energy it uses is:", "600 J", ["6 J", "70 J", "0.6 J"], "Energy = power × time = 60 × 10 = 600 J."],
  ],
  "s9-atom": [
    ["easy", "Which subatomic particle carries a negative charge?", "Electron", ["Proton", "Neutron", "Nucleus"], "Electrons are negatively charged and move around the nucleus."],
    ["easy", "Rutherford's gold foil experiment showed that an atom has:", "A small, dense, positive nucleus", ["No empty space", "Electrons inside a positive pudding", "No charge at all"], "Most alpha particles passed through, but a few bounced back from a tiny dense centre."],
    ["medium", "The maximum number of electrons in the L shell is:", "8", ["2", "18", "32"], "Using 2n², for n = 2 the L shell holds 8 electrons."],
    ["medium", "Isotopes of an element have the same:", "Atomic number", ["Mass number", "Number of neutrons", "Atomic mass"], "Isotopes have equal protons but different neutrons."],
    ["hard", "The valency of sodium (atomic number 11) is:", "1", ["2", "7", "3"], "Configuration 2, 8, 1 — it loses one electron to attain an octet."],
    ["hard", "Calcium-40 and Argon-40 are examples of:", "Isobars", ["Isotopes", "Isomers", "Allotropes"], "Isobars have the same mass number but different atomic numbers."],
  ],
  "s9-matter": [
    ["easy", "Who proposed that matter is made of indivisible atoms (atomic theory)?", "John Dalton", ["J.J. Thomson", "Niels Bohr", "Lavoisier"], "Dalton's atomic theory explained the laws of chemical combination."],
    ["easy", "The chemical formula of water shows it contains:", "2 hydrogen atoms and 1 oxygen atom", ["1 hydrogen and 2 oxygen atoms", "Only hydrogen", "1 hydrogen and 1 oxygen"], "H₂O has two H atoms bonded to one O atom."],
    ["medium", "In water, hydrogen and oxygen are always combined in a mass ratio of 1:8. This illustrates the law of:", "Constant proportions", ["Conservation of mass", "Multiple proportions", "Octaves"], "A compound always contains its elements in a fixed ratio by mass."],
    ["medium", "The molecular mass of CO₂ (C = 12 u, O = 16 u) is:", "44 u", ["28 u", "32 u", "40 u"], "12 + 2 × 16 = 44 u."],
    ["hard", "The correct formula of aluminium oxide (Al³⁺, O²⁻) is:", "Al₂O₃", ["AlO", "Al₃O₂", "AlO₃"], "Criss-cross the valencies 3 and 2 to balance the charges."],
  ],
  "s9-sound": [
    ["easy", "Sound cannot travel through:", "Vacuum", ["Water", "Steel", "Air"], "Sound is a mechanical wave and needs a medium."],
    ["easy", "The audible range of frequencies for humans is about:", "20 Hz to 20,000 Hz", ["2 Hz to 200 Hz", "20 kHz to 200 kHz", "0 Hz to 20 Hz"], "Below 20 Hz is infrasound and above 20 kHz is ultrasound."],
    ["medium", "Sound waves in air are:", "Longitudinal", ["Transverse", "Electromagnetic", "Stationary only"], "Particles vibrate along the direction of travel forming compressions and rarefactions."],
    ["medium", "Pitch of a sound depends on its:", "Frequency", ["Amplitude", "Speed", "Medium only"], "Higher frequency gives a higher pitch; amplitude decides loudness."],
    ["hard", "A wave has frequency 500 Hz and wavelength 0.68 m. Its speed is:", "340 m/s", ["735 m/s", "0.00136 m/s", "500.68 m/s"], "v = fλ = 500 × 0.68 = 340 m/s."],
    ["hard", "To hear a distinct echo in air (speed 344 m/s), the reflecting surface must be at least about:", "17.2 m away", ["34.4 m away", "1 m away", "100 m away"], "The echo must return after at least 0.1 s: distance = 344 × 0.1 ÷ 2 ≈ 17.2 m."],
  ],
  "s9-reproduction": [
    ["easy", "Which part of a flower is the male reproductive organ?", "Stamen", ["Pistil", "Sepal", "Petal"], "The stamen has an anther producing pollen and a filament."],
    ["easy", "Transfer of pollen from anther to stigma is called:", "Pollination", ["Fertilisation", "Germination", "Dispersal"], "Pollination happens before fertilisation."],
    ["medium", "Producing offspring from a single parent without gametes is:", "Asexual reproduction", ["Sexual reproduction", "Cross-pollination", "Fertilisation"], "Examples include budding, fission and vegetative propagation."],
    ["medium", "After fertilisation, the ovary of a flower develops into the:", "Fruit", ["Seed", "Petal", "Stamen"], "Ovules become seeds and the ovary becomes the fruit."],
    ["hard", "In humans, fertilisation normally takes place in the:", "Fallopian tube (oviduct)", ["Uterus", "Ovary", "Cervix"], "The sperm meets the egg in the oviduct; the zygote then implants in the uterus."],
  ],
  "s9-diversity": [
    ["easy", "The five kingdom classification was proposed by:", "R.H. Whittaker", ["Carl Linnaeus", "Charles Darwin", "Ernst Haeckel"], "Whittaker (1969) proposed Monera, Protista, Fungi, Plantae and Animalia."],
    ["easy", "In binomial nomenclature, the first word is the:", "Genus", ["Species", "Family", "Kingdom"], "E.g., Homo sapiens: Homo is the genus, sapiens the species."],
    ["medium", "Bacteria belong to the kingdom:", "Monera", ["Protista", "Fungi", "Plantae"], "Monera includes unicellular prokaryotes."],
    ["medium", "Plants that bear naked seeds (not enclosed in fruits) are:", "Gymnosperms", ["Angiosperms", "Bryophytes", "Pteridophytes"], "Gymnosperm means 'naked seed', e.g., pine."],
    ["hard", "Viruses are not placed in any of the five kingdoms mainly because they:", "Show life only inside a host cell", ["Are multicellular", "Have a cell wall of chitin", "Make their own food"], "Viruses are acellular and reproduce only by using a host cell."],
  ],
  "s9-earth": [
    ["easy", "The layer of gases surrounding the Earth is the:", "Atmosphere", ["Hydrosphere", "Lithosphere", "Biosphere"], "Atmosphere = air; hydrosphere = water; lithosphere = rock."],
    ["easy", "During the day, a breeze blowing from the sea to the land is a:", "Sea breeze", ["Land breeze", "Monsoon reversal", "Trade wind"], "Land heats faster, air above it rises, and cooler sea air moves in."],
    ["medium", "Land and sea breezes happen mainly because of:", "Different heating of land and water", ["Earth's rotation only", "Tides", "Volcanic activity"], "Water has a higher specific heat, so it heats and cools more slowly than land."],
    ["medium", "Which process removes carbon dioxide from the atmosphere?", "Photosynthesis", ["Respiration", "Burning fuels", "Decomposition"], "Plants fix CO₂ into glucose using sunlight."],
    ["hard", "Which part of solar radiation is mostly absorbed by the ozone layer?", "Ultraviolet rays", ["Visible light", "Radio waves", "Infrared only"], "Ozone in the stratosphere absorbs harmful UV radiation."],
  ],

  "s10-reactions": [
    ["easy", "2Mg + O₂ → 2MgO is an example of a:", "Combination reaction", ["Decomposition reaction", "Displacement reaction", "Double displacement reaction"], "Two reactants combine to form a single product."],
    ["easy", "Rusting of iron is an example of:", "Corrosion", ["Rancidity", "Neutralisation", "Sublimation"], "Iron slowly reacts with oxygen and moisture to form hydrated iron oxide."],
    ["medium", "Fe + CuSO₄ → FeSO₄ + Cu is a:", "Displacement reaction", ["Combination reaction", "Decomposition reaction", "Double displacement reaction"], "More reactive iron displaces copper from its salt solution."],
    ["medium", "In CuO + H₂ → Cu + H₂O, the substance oxidised is:", "H₂", ["CuO", "Cu", "H₂O"], "Hydrogen gains oxygen to form water, so it is oxidised."],
    ["hard", "Decomposition of calcium carbonate into CaO and CO₂ on heating is a:", "Thermal decomposition and endothermic reaction", ["Exothermic combination", "Photolytic decomposition", "Displacement reaction"], "Heat is absorbed to break CaCO₃ down."],
    ["hard", "Chips packets are flushed with nitrogen to prevent:", "Rancidity", ["Corrosion", "Neutralisation", "Displacement"], "Nitrogen prevents oxidation of fats and oils."],
  ],
  "s10-acids": [
    ["easy", "An acid turns blue litmus:", "Red", ["Blue", "Green", "Colourless"], "Acids turn blue litmus red; bases turn red litmus blue."],
    ["easy", "A solution with pH 7 is:", "Neutral", ["Strongly acidic", "Strongly basic", "Weakly acidic"], "pH below 7 is acidic, above 7 is basic."],
    ["medium", "Acid + base → salt + water is called:", "Neutralisation", ["Oxidation", "Hydrolysis", "Combustion"], "H⁺ ions from the acid combine with OH⁻ ions from the base."],
    ["medium", "The chemical formula of baking soda is:", "NaHCO₃", ["Na₂CO₃", "CaOCl₂", "NaCl"], "Sodium hydrogencarbonate; washing soda is Na₂CO₃·10H₂O."],
    ["hard", "Plaster of Paris is obtained by heating:", "Gypsum (CaSO₄·2H₂O)", ["Limestone", "Bleaching powder", "Washing soda"], "Heating gypsum at 373 K gives CaSO₄·½H₂O."],
    ["hard", "Tooth decay starts when the pH in the mouth falls below about:", "5.5", ["7.5", "9", "12"], "Below pH 5.5 tooth enamel (calcium phosphate) starts to corrode."],
  ],
  "s10-metals": [
    ["easy", "Which metal is liquid at room temperature?", "Mercury", ["Sodium", "Iron", "Aluminium"], "Mercury is the only metal that is liquid at room temperature."],
    ["easy", "The best conductors of electricity among these are:", "Silver and copper", ["Lead and mercury", "Iodine and carbon", "Sulphur and phosphorus"], "Silver and copper are the best conductors."],
    ["medium", "Which metal is stored under kerosene because it reacts vigorously with air and water?", "Sodium", ["Copper", "Gold", "Zinc"], "Sodium and potassium catch fire in air, so they are kept in kerosene."],
    ["medium", "Ionic compounds generally have:", "High melting points", ["Low melting points", "No charges", "Only covalent bonds"], "Strong electrostatic attraction between ions needs a lot of energy to break."],
    ["hard", "Galvanisation protects iron by coating it with:", "Zinc", ["Tin", "Copper", "Chromium"], "Zinc prevents rusting even when the coating is scratched."],
    ["hard", "Highly reactive metals like sodium are extracted by:", "Electrolytic reduction", ["Heating with carbon", "Roasting alone", "Heating in air"], "Carbon cannot reduce oxides of very reactive metals."],
  ],
  "s10-carbon": [
    ["easy", "Carbon mainly forms which type of bonds?", "Covalent bonds", ["Ionic bonds", "Metallic bonds", "Hydrogen bonds only"], "Carbon shares electrons because gaining or losing four is difficult."],
    ["easy", "The property of carbon to form long chains with itself is:", "Catenation", ["Tetravalency", "Isomerism", "Allotropy"], "Catenation gives rise to a huge number of carbon compounds."],
    ["medium", "Successive members of a homologous series differ by:", "–CH₂–", ["–CH₃", "–OH", "–COOH"], "Each member differs by one CH₂ unit (14 u)."],
    ["medium", "The functional group in ethanoic acid is:", "–COOH (carboxylic acid)", ["–OH (alcohol)", "–CHO (aldehyde)", "–CO– (ketone)"], "Ethanoic acid is CH₃COOH."],
    ["hard", "Converting vegetable oil into vanaspati ghee using nickel catalyst is an:", "Addition (hydrogenation) reaction", ["Substitution reaction", "Oxidation reaction", "Combustion reaction"], "Hydrogen adds across C=C double bonds."],
    ["hard", "Soaps do not lather well in hard water because:", "They form insoluble scum with Ca²⁺ and Mg²⁺", ["Hard water is acidic", "Soap evaporates", "Hard water has no ions"], "Calcium and magnesium salts of fatty acids precipitate as scum."],
  ],
  "s10-periodic": [
    ["easy", "Mendeléev arranged elements in increasing order of:", "Atomic mass", ["Atomic number", "Valency", "Density"], "The modern table uses atomic number instead."],
    ["easy", "The modern periodic table is based on:", "Atomic number", ["Atomic mass", "Number of neutrons", "Density"], "Moseley showed atomic number is the fundamental property."],
    ["medium", "Moving left to right across a period, atomic size generally:", "Decreases", ["Increases", "Stays the same", "Doubles"], "Increasing nuclear charge pulls electrons closer."],
    ["medium", "Newlands' law of octaves worked well only up to:", "Calcium", ["Iron", "Uranium", "Neon"], "After calcium, every eighth element did not show similar properties."],
    ["hard", "Elements in the same group have the same:", "Number of valence electrons", ["Atomic mass", "Number of shells", "Number of neutrons"], "Same valence electrons give similar chemical properties."],
  ],
  "s10-life": [
    ["easy", "The site of photosynthesis in a plant cell is the:", "Chloroplast", ["Mitochondria", "Nucleus", "Vacuole"], "Chlorophyll in chloroplasts captures sunlight."],
    ["easy", "The functional unit of the human kidney is the:", "Nephron", ["Neuron", "Alveolus", "Villus"], "Each kidney contains about a million nephrons that filter blood."],
    ["medium", "Gas exchange in human lungs takes place in the:", "Alveoli", ["Trachea", "Bronchi", "Larynx"], "Thin-walled alveoli surrounded by capillaries allow O₂ and CO₂ exchange."],
    ["medium", "Muscle cramps after heavy exercise are due to the build-up of:", "Lactic acid", ["Ethanol", "Carbon dioxide only", "Glucose"], "Lack of oxygen causes anaerobic respiration in muscles."],
    ["hard", "Which blood vessel carries oxygenated blood from the lungs to the heart?", "Pulmonary vein", ["Pulmonary artery", "Vena cava", "Aorta"], "It is the only vein carrying oxygenated blood."],
    ["hard", "Food is transported in plants through the phloem by a process called:", "Translocation", ["Transpiration", "Osmosis only", "Guttation"], "Phloem moves sugars using energy from ATP."],
  ],
  "s10-control": [
    ["easy", "The basic unit of the nervous system is the:", "Neuron", ["Nephron", "Alveolus", "Axon only"], "Neurons carry electrical impulses."],
    ["easy", "Quickly pulling your hand away from a hot object is a:", "Reflex action", ["Voluntary action", "Hormonal action", "Tropism"], "Reflexes are controlled by the spinal cord for speed."],
    ["medium", "Which part of the brain maintains posture and balance?", "Cerebellum", ["Cerebrum", "Medulla", "Hypothalamus"], "The cerebellum coordinates precise voluntary movements and balance."],
    ["medium", "Which plant hormone promotes cell division?", "Cytokinin", ["Abscisic acid", "Ethylene", "Auxin only"], "Cytokinins are high in fruits and seeds where cells divide rapidly."],
    ["hard", "Insulin is secreted by the:", "Pancreas", ["Thyroid", "Adrenal gland", "Pituitary"], "Insulin regulates blood sugar; deficiency causes diabetes."],
    ["hard", "Iodised salt is recommended to prevent:", "Goitre", ["Diabetes", "Dwarfism", "Night blindness"], "Iodine is needed by the thyroid to make thyroxin."],
  ],
  "s10-repro": [
    ["easy", "Amoeba reproduces by:", "Binary fission", ["Budding", "Spore formation", "Fragmentation"], "The parent cell splits into two daughter cells."],
    ["easy", "Hydra reproduces asexually by:", "Budding", ["Binary fission", "Seeds", "Spores"], "An outgrowth develops and detaches as a new hydra."],
    ["medium", "Bryophyllum can produce new plants from its:", "Leaf margins", ["Seeds only", "Flowers", "Pollen"], "Buds on leaf margins grow into new plants (vegetative propagation)."],
    ["medium", "In flowering plants, fertilisation produces a:", "Zygote", ["Pollen grain", "Anther", "Stigma"], "The male and female gametes fuse in the ovule to form a zygote."],
    ["hard", "Which contraceptive method also protects against sexually transmitted infections?", "Condom (barrier method)", ["Oral pills", "Copper-T", "Surgical methods"], "Barrier methods prevent contact between body fluids."],
  ],
  "s10-heredity": [
    ["easy", "Mendel performed his experiments on:", "Garden pea", ["Fruit fly", "Maize", "Bacteria"], "Pea plants show clear contrasting traits and are easy to cross."],
    ["easy", "A trait that is expressed even with one copy of the gene is:", "Dominant", ["Recessive", "Acquired", "Neutral"], "Dominant alleles mask recessive ones."],
    ["medium", "In a monohybrid cross (Tt × Tt), the F2 phenotypic ratio is:", "3 : 1", ["1 : 2 : 1", "9 : 3 : 3 : 1", "1 : 1"], "Three tall plants for every one short plant."],
    ["medium", "A child who inherits an X chromosome from the father will be:", "A girl", ["A boy", "Either, randomly", "Decided by the mother only"], "XX is female; the father gives X (girl) or Y (boy)."],
    ["hard", "The F2 genotypic ratio of a monohybrid cross is:", "1 : 2 : 1", ["3 : 1", "9 : 3 : 3 : 1", "2 : 1"], "TT : Tt : tt = 1 : 2 : 1."],
  ],
  "s10-light": [
    ["easy", "The image formed by a plane mirror is:", "Virtual and erect", ["Real and inverted", "Real and erect", "Virtual and inverted"], "It is the same size and laterally inverted."],
    ["easy", "A concave mirror is used as a:", "Shaving mirror", ["Rear-view mirror in vehicles", "Plane mirror", "Prism"], "Close to a concave mirror the image is enlarged and erect."],
    ["medium", "The focal length of a spherical mirror with radius of curvature 20 cm is:", "10 cm", ["20 cm", "40 cm", "5 cm"], "f = R/2."],
    ["medium", "Refractive index of a medium is the ratio:", "Speed of light in vacuum ÷ speed of light in the medium", ["Speed in medium ÷ speed in vacuum", "Angle of incidence × angle of refraction", "Focal length ÷ radius"], "n = c/v."],
    ["hard", "The power of a convex lens with focal length 50 cm is:", "+2 D", ["−2 D", "+0.5 D", "+50 D"], "P = 1/f (in metres) = 1/0.5 = +2 D."],
    ["hard", "An object is placed at 2F in front of a convex lens. The image is:", "Real, inverted and same size at 2F", ["Virtual and enlarged", "At infinity", "Real and highly diminished at F"], "At 2F the image forms at 2F on the other side, same size."],
  ],
  "s10-eye": [
    ["easy", "The image in a human eye is formed on the:", "Retina", ["Cornea", "Iris", "Pupil"], "The retina has light-sensitive rods and cones."],
    ["easy", "Myopia (short-sightedness) is corrected using a:", "Concave lens", ["Convex lens", "Bifocal only", "Plane glass"], "A diverging lens moves the image back onto the retina."],
    ["medium", "The ability of the eye lens to change its focal length is called:", "Power of accommodation", ["Persistence of vision", "Dispersion", "Refraction"], "Ciliary muscles change the lens curvature."],
    ["medium", "Splitting of white light into seven colours by a prism is:", "Dispersion", ["Reflection", "Scattering", "Total internal reflection"], "Different colours bend by different amounts."],
    ["hard", "The sky appears blue because:", "Blue light is scattered more by air molecules", ["The ocean reflects blue", "Red light is absorbed by clouds", "Blue light has the longest wavelength"], "Shorter wavelengths scatter more strongly."],
    ["hard", "Stars twinkle because of:", "Atmospheric refraction", ["Dispersion in the eye", "Reflection from clouds", "Scattering by dust only"], "Changing air density keeps bending starlight slightly."],
  ],
  "s10-electricity": [
    ["easy", "The SI unit of electric current is the:", "Ampere", ["Volt", "Ohm", "Watt"], "1 A = 1 coulomb per second."],
    ["easy", "An ammeter is connected in a circuit in:", "Series", ["Parallel", "Either way", "Across the battery only"], "It must carry the full current it measures."],
    ["medium", "A 12 V battery drives a current of 2 A through a resistor. Its resistance is:", "6 Ω", ["24 Ω", "0.17 Ω", "14 Ω"], "R = V/I = 12/2 = 6 Ω."],
    ["medium", "Three 6 Ω resistors are connected in parallel. The equivalent resistance is:", "2 Ω", ["18 Ω", "6 Ω", "3 Ω"], "1/R = 1/6 + 1/6 + 1/6 = 1/2, so R = 2 Ω."],
    ["hard", "If the length of a wire is doubled (same material and thickness), its resistance:", "Doubles", ["Halves", "Stays the same", "Becomes four times"], "R = ρL/A, so R is proportional to length."],
    ["hard", "A 1000 W heater runs for 2 hours. The energy used is:", "2 kWh", ["2000 kWh", "500 Wh", "0.5 kWh"], "Energy = 1 kW × 2 h = 2 kWh (2 units)."],
  ],
  "s10-magnetic": [
    ["easy", "Magnetic field lines outside a bar magnet go from:", "North pole to south pole", ["South pole to north pole", "Centre outward only", "Nowhere"], "Inside the magnet they go from south to north, forming closed loops."],
    ["easy", "A current-carrying solenoid behaves like a:", "Bar magnet", ["Battery", "Resistor", "Capacitor"], "It has a north and south pole at its ends."],
    ["medium", "The direction of force on a current-carrying conductor in a magnetic field is given by:", "Fleming's left-hand rule", ["Fleming's right-hand rule", "Ohm's law", "Snell's law"], "Thumb = force, forefinger = field, middle finger = current."],
    ["medium", "Magnetic field lines never intersect because:", "The field would have two directions at one point", ["They are too weak", "They are parallel always", "Magnets have one pole"], "A compass can point in only one direction at any point."],
    ["hard", "In Indian domestic supply, the AC frequency is:", "50 Hz", ["60 Hz", "220 Hz", "100 Hz"], "The supply is 220 V at 50 Hz."],
    ["hard", "The safety device that melts when excess current flows is a:", "Fuse", ["Earth wire", "Switch", "Ammeter"], "It protects appliances from overloading and short circuits."],
  ],
  "s10-environment": [
    ["easy", "Organisms that make their own food are called:", "Producers", ["Consumers", "Decomposers", "Scavengers"], "Green plants make food by photosynthesis."],
    ["easy", "Which of these is biodegradable?", "Vegetable peels", ["Plastic bags", "Glass bottles", "Aluminium cans"], "Microorganisms can break down natural organic waste."],
    ["medium", "Only about how much energy is passed on to the next trophic level?", "10%", ["50%", "90%", "1%"], "This is the 10% law; the rest is lost mainly as heat."],
    ["medium", "The increase in concentration of harmful chemicals at higher trophic levels is:", "Biological magnification", ["Eutrophication", "Decomposition", "Photosynthesis"], "Non-biodegradable pesticides accumulate up the food chain."],
    ["hard", "Ozone layer depletion is mainly caused by:", "Chlorofluorocarbons (CFCs)", ["Carbon monoxide", "Nitrogen gas", "Water vapour"], "CFCs release chlorine that breaks down ozone in the stratosphere."],
  ],
};

export const SCIENCE_CARDS: Record<string, [string, string][]> = {
  "s9-exploration": [["Hypothesis", "A testable explanation that can be supported or rejected"], ["Independent variable", "The factor you change on purpose"], ["Dependent variable", "The factor you measure"], ["Inference", "A conclusion drawn from observations"]],
  "s9-cell": [["Mitochondria", "Powerhouse of the cell — releases energy as ATP"], ["Osmosis", "Movement of water through a selectively permeable membrane"], ["Plasmolysis", "Shrinking of cytoplasm when a cell loses water"], ["Lysosome", "Suicide bag of the cell — has digestive enzymes"]],
  "s9-tissues": [["Meristem", "Dividing plant tissue at growing tips"], ["Phloem", "Carries food in plants"], ["Ligament", "Connects bone to bone"], ["Cardiac muscle", "Involuntary, striated muscle of the heart"]],
  "s9-motion": [["Displacement", "Shortest distance from start to end with direction"], ["Acceleration", "Rate of change of velocity (m/s²)"], ["v = u + at", "First equation of motion"], ["Slope of v–t graph", "Acceleration"]],
  "s9-mixtures": [["Colloid", "Mixture whose particles scatter light but don't settle"], ["Tyndall effect", "Scattering of light by colloidal particles"], ["Chromatography", "Separating dyes by different speeds on paper"], ["Sublimation", "Solid turning directly into vapour"]],
  "s9-forces": [["Inertia", "Tendency to resist change in state of motion"], ["F = ma", "Newton's second law"], ["Third law", "Every action has an equal and opposite reaction"], ["1 newton", "Force giving 1 kg an acceleration of 1 m/s²"]],
  "s9-work": [["Work", "W = F × s (joule)"], ["Kinetic energy", "½mv²"], ["Potential energy", "mgh"], ["Power", "Work done per second (watt)"]],
  "s9-atom": [["Isotopes", "Same atomic number, different mass number"], ["Isobars", "Same mass number, different atomic number"], ["Valency", "Combining capacity of an atom"], ["2n²", "Maximum electrons in a shell"]],
  "s9-matter": [["Law of constant proportions", "A compound has elements in a fixed mass ratio"], ["Molecule", "Smallest particle of a substance that can exist independently"], ["Ion", "Charged atom or group of atoms"], ["Molecular mass", "Sum of atomic masses in a molecule"]],
  "s9-sound": [["Frequency", "Number of vibrations per second (Hz)"], ["Echo", "Reflected sound heard after ≥ 0.1 s"], ["Ultrasound", "Frequencies above 20 kHz"], ["v = fλ", "Wave speed formula"]],
  "s9-reproduction": [["Stamen", "Male part of a flower"], ["Pistil", "Female part of a flower"], ["Pollination", "Pollen moves from anther to stigma"], ["Zygote", "Cell formed after fertilisation"]],
  "s9-diversity": [["Binomial nomenclature", "Genus + species naming"], ["Monera", "Kingdom of prokaryotes"], ["Gymnosperm", "Plant with naked seeds"], ["Whittaker", "Proposed five kingdom classification"]],
  "s9-earth": [["Hydrosphere", "All the water on Earth"], ["Sea breeze", "Daytime breeze from sea to land"], ["Ozone layer", "Absorbs harmful UV radiation"], ["Carbon cycle", "Movement of carbon between air, life and land"]],
  "s10-reactions": [["Oxidation", "Gain of oxygen or loss of hydrogen"], ["Displacement", "More reactive element replaces a less reactive one"], ["Rancidity", "Oxidation of fats making food smell bad"], ["Exothermic", "Reaction releasing heat"]],
  "s10-acids": [["pH < 7", "Acidic"], ["Baking soda", "NaHCO₃"], ["Washing soda", "Na₂CO₃·10H₂O"], ["Bleaching powder", "CaOCl₂"]],
  "s10-metals": [["Reactivity series", "Metals arranged by decreasing reactivity"], ["Galvanisation", "Coating iron with zinc"], ["Alloy", "Homogeneous mixture of metals (e.g., brass)"], ["Roasting", "Heating sulphide ore in excess air"]],
  "s10-carbon": [["Catenation", "Carbon bonding to itself in chains"], ["Homologous series", "Members differ by –CH₂–"], ["Esterification", "Acid + alcohol → ester"], ["Micelle", "Soap cluster that traps oily dirt"]],
  "s10-periodic": [["Döbereiner's triads", "Groups of three similar elements"], ["Mendeléev", "Arranged elements by atomic mass"], ["Modern periodic law", "Properties depend on atomic number"], ["Period trend", "Atomic size decreases left to right"]],
  "s10-life": [["Nephron", "Filtering unit of the kidney"], ["Alveoli", "Air sacs where gas exchange happens"], ["Translocation", "Transport of food in phloem"], ["Transpiration", "Loss of water vapour from leaves"]],
  "s10-control": [["Reflex arc", "Pathway of a reflex action"], ["Cerebellum", "Balance and posture"], ["Auxin", "Plant hormone for growth towards light"], ["Thyroxin", "Hormone needing iodine"]],
  "s10-repro": [["Binary fission", "Splitting into two (Amoeba)"], ["Budding", "New organism from an outgrowth (Hydra, yeast)"], ["Vegetative propagation", "New plants from roots, stems or leaves"], ["Placenta", "Links the embryo to the mother's blood"]],
  "s10-heredity": [["Allele", "Alternative form of a gene"], ["3 : 1", "F2 phenotypic ratio of a monohybrid cross"], ["XY", "Male sex chromosomes"], ["Recessive trait", "Shows only when both alleles are recessive"]],
  "s10-light": [["f = R/2", "Focal length of a spherical mirror"], ["Mirror formula", "1/v + 1/u = 1/f"], ["Lens formula", "1/v − 1/u = 1/f"], ["Power of lens", "P = 1/f (dioptre)"]],
  "s10-eye": [["Myopia", "Near-sightedness, corrected by concave lens"], ["Hypermetropia", "Far-sightedness, corrected by convex lens"], ["Dispersion", "Splitting of white light into colours"], ["Tyndall effect", "Scattering of light by particles"]],
  "s10-electricity": [["Ohm's law", "V = IR"], ["Resistivity", "ρ — property of the material"], ["Series resistors", "R = R₁ + R₂ + …"], ["1 kWh", "1 unit = 3.6 × 10⁶ J"]],
  "s10-magnetic": [["Solenoid", "Coil that behaves like a bar magnet"], ["Fleming's left-hand rule", "Direction of force on a conductor"], ["Fuse", "Melts when current is too high"], ["Earth wire", "Safety wire for metal-bodied appliances"]],
  "s10-environment": [["Producer", "Makes its own food"], ["10% law", "Only 10% energy passes to the next level"], ["Biomagnification", "Toxins increase up the food chain"], ["CFCs", "Chemicals that deplete ozone"]],
};
