import type { RawQuestion } from "./bank-types";

export const MATHS10_MORE: Record<string, RawQuestion[]> = {
  "m10-real": [
    ["easy", "The HCF of 26 and 91 is:", "13", ["7", "182", "1"], "26 = 2 × 13 and 91 = 7 × 13, so the only common prime factor is 13."],
    ["easy", "The exponent of 2 in the prime factorisation of 144 is:", "4", ["2", "3", "6"], "144 = 16 × 9 = 2⁴ × 3²."],
    ["easy", "If p is a prime number, then √p is:", "Irrational", ["Rational", "An integer", "A natural number"], "The square root of any prime is irrational, as proved for √2, √3 and √5."],
    ["medium", "The LCM of 12, 15 and 21 is:", "420", ["3780", "60", "210"], "12 = 2² × 3, 15 = 3 × 5, 21 = 3 × 7; LCM = 2² × 3 × 5 × 7 = 420."],
    ["medium", "Given HCF(306, 657) = 9, the LCM(306, 657) is:", "22338", ["2754", "5913", "201042"], "LCM = (306 × 657) ÷ 9 = 201042 ÷ 9 = 22338."],
    ["medium", "The number (2 + √3)(2 − √3) is:", "1, a rational number", ["√3, an irrational number", "4 − √3, an irrational number", "7, a rational number"], "(2 + √3)(2 − √3) = 2² − (√3)² = 4 − 3 = 1."],
    ["medium", "For which natural number n does 6ⁿ end with the digit 0?", "For no natural number n", ["n = 5", "Every even n", "n = 10"], "6ⁿ = 2ⁿ × 3ⁿ has no prime factor 5, so it can never end in 0."],
    ["medium", "Two bells ring at intervals of 18 minutes and 24 minutes. If they ring together at 9:00 am, they next ring together at:", "10:12 am", ["9:42 am", "9:06 am", "10:24 am"], "LCM(18, 24) = 2³ × 3² = 72 minutes after 9:00 am, i.e., 10:12 am."],
    ["hard", "Assertion (A): If HCF(12, 18) = 6, then LCM(12, 18) = 36. Reason (R): For any two positive integers a and b, HCF(a, b) × LCM(a, b) = a × b.", "Both A and R are true, and R is the correct explanation of A", ["Both A and R are true, but R is not the correct explanation of A", "A is true, but R is false", "A is false, but R is true"], "By R, LCM = (12 × 18) ÷ 6 = 216 ÷ 6 = 36, so R directly gives A."],
    ["hard", "If a = 2³ × 3² and b = 2² × 3³ × 5, then LCM(a, b) ÷ HCF(a, b) is:", "30", ["1080", "36", "6"], "HCF = 2² × 3² = 36 and LCM = 2³ × 3³ × 5 = 1080; 1080 ÷ 36 = 30."],
    ["hard", "Assertion (A): 5 − √3 is irrational. Reason (R): The difference of two irrational numbers is always irrational.", "A is true, but R is false", ["Both A and R are true, and R is the correct explanation of A", "Both A and R are true, but R is not the correct explanation of A", "A is false, but R is true"], "A rational minus a non-zero irrational is irrational, so A is true; R is false since √3 − √3 = 0."],
  ],
  "m10-poly": [
    ["easy", "The zeros of the polynomial x² − 3x are:", "0 and 3", ["3 only", "0 and −3", "1 and 3"], "x² − 3x = x(x − 3), so x = 0 or x = 3."],
    ["easy", "If the graph of y = p(x) does not meet the x-axis at all, the number of zeros of p(x) is:", "0", ["1", "2", "Infinitely many"], "Zeros are the x-coordinates where the graph meets the x-axis; no meeting point means no zeros."],
    ["easy", "The zero of the linear polynomial 2x − 8 is:", "4", ["−4", "8", "2"], "2x − 8 = 0 gives x = 4."],
    ["easy", "The sum of the zeros of 2x² − 8x + 6 is:", "4", ["−4", "3", "8"], "Sum = −b/a = −(−8)/2 = 4."],
    ["medium", "The product of the zeros of 3x² + 5x − 2 is:", "−2/3", ["2/3", "−5/3", "5/3"], "Product = c/a = −2/3 (the zeros are 1/3 and −2)."],
    ["medium", "If 2 is a zero of x² − kx + 8, then k is:", "6", ["−6", "4", "8"], "4 − 2k + 8 = 0 gives k = 6; the zeros are 2 and 4."],
    ["medium", "A quadratic polynomial whose zeros are −2 and 5 is:", "x² − 3x − 10", ["x² + 3x − 10", "x² − 3x + 10", "x² − 7x + 10"], "Sum = 3 and product = −10, so x² − 3x − 10."],
    ["medium", "The zeros of 6x² − 7x − 3 are:", "3/2 and −1/3", ["−3/2 and 1/3", "3 and −1", "3/2 and 1/3"], "6x² − 9x + 2x − 3 = (2x − 3)(3x + 1), so x = 3/2 or x = −1/3."],
    ["medium", "If α and β are the zeros of x² − 5x + 4, then 1/α + 1/β is:", "5/4", ["4/5", "−5/4", "5"], "1/α + 1/β = (α + β)/αβ = 5/4."],
    ["hard", "If α and β are the zeros of x² − 6x + 7, then α² + β² is:", "22", ["50", "36", "29"], "α² + β² = (α + β)² − 2αβ = 36 − 14 = 22."],
    ["hard", "Assertion (A): The polynomial x² + 4x + 5 has no real zeros. Reason (R): The graph of y = x² + 4x + 5 lies entirely above the x-axis.", "Both A and R are true, and R is the correct explanation of A", ["Both A and R are true, but R is not the correct explanation of A", "A is true, but R is false", "A is false, but R is true"], "x² + 4x + 5 = (x + 2)² + 1 > 0, so the graph never meets the x-axis and there are no real zeros."],
    ["hard", "If one zero of 2x² + 3x + k is the reciprocal of the other, then k is:", "2", ["1/2", "3", "−2"], "Product of zeros = α × (1/α) = 1 = k/2, so k = 2."],
  ],
  "m10-linear": [
    ["easy", "If the lines representing a pair of linear equations are coincident, the pair has:", "Infinitely many solutions", ["No solution", "Exactly one solution", "Exactly two solutions"], "Coincident lines share every point, so every point is a solution."],
    ["easy", "The lines x = 3 and y = −2 intersect at:", "(3, −2)", ["(−2, 3)", "(0, 0)", "(3, 0)"], "The point on both lines has x = 3 and y = −2."],
    ["easy", "Which ordered pair satisfies 3x − y = 7?", "(2, −1)", ["(2, 1)", "(1, 4)", "(3, 1)"], "3(2) − (−1) = 6 + 1 = 7."],
    ["easy", "If x = 1, y = 2 is a solution of 2x + y = k, then k is:", "4", ["3", "5", "2"], "k = 2(1) + 2 = 4."],
    ["medium", "The pair x + 2y = 4 and 2x + 4y = 12 has:", "No solution", ["Infinitely many solutions", "A unique solution", "Exactly two solutions"], "a₁/a₂ = b₁/b₂ = 1/2 but c₁/c₂ = 4/12 = 1/3, so the lines are parallel."],
    ["medium", "Solving 3x + 2y = 11 and 2x − 2y = 4 by elimination gives:", "x = 3, y = 1", ["x = 1, y = 3", "x = 3, y = −1", "x = 2, y = 2.5"], "Adding gives 5x = 15, so x = 3; then 2y = 11 − 9 = 2, so y = 1."],
    ["medium", "For what value of k do 2x + ky = 3 and 4x + 6y = 6 have infinitely many solutions?", "k = 3", ["k = 6", "k = 2", "k = 12"], "Need 2/4 = k/6 = 3/6, so k/6 = 1/2 and k = 3."],
    ["medium", "The pair 3x + ky = 7 and 6x − 4y = 1 has a unique solution when:", "k ≠ −2", ["k = −2", "k ≠ 2", "k = 2"], "Unique solution needs 3/6 ≠ k/(−4), i.e., k ≠ −2."],
    ["medium", "5 pens and 2 notebooks cost ₹110, while 2 pens and 1 notebook cost ₹50. The cost of one notebook is:", "₹30", ["₹10", "₹20", "₹25"], "From 2p + n = 50, n = 50 − 2p; then 5p + 100 − 4p = 110 gives p = 10 and n = 30."],
    ["hard", "The sum of the digits of a two-digit number is 9. Reversing the digits gives a number 27 more than the original. The number is:", "36", ["63", "45", "27"], "x + y = 9 and (10y + x) − (10x + y) = 27 give y − x = 3, so x = 3, y = 6 and the number is 36."],
    ["hard", "Assertion (A): The lines 2x − 3y = 8 and 4x − 6y = 9 are parallel. Reason (R): If a₁/a₂ = b₁/b₂ ≠ c₁/c₂, the pair of equations has no solution.", "Both A and R are true, and R is the correct explanation of A", ["Both A and R are true, but R is not the correct explanation of A", "A is true, but R is false", "A is false, but R is true"], "Here 2/4 = −3/−6 = 1/2 ≠ 8/9, so by R the lines never meet, i.e., they are parallel."],
    ["hard", "For what values of a and b do 2x + 3y = 7 and (a − b)x + (a + b)y = 3a + b − 2 have infinitely many solutions?", "a = 5, b = 1", ["a = 1, b = 5", "a = 5, b = −1", "a = 3, b = 1"], "Need 2/(a − b) = 3/(a + b) = 7/(3a + b − 2); a − b = 4, a + b = 6 give a = 5, b = 1, and 7/14 = 1/2 checks."],
  ],
  "m10-quadratic": [
    ["easy", "The standard form of a quadratic equation is:", "ax² + bx + c = 0, where a ≠ 0", ["ax² + bx + c = 0, where a = 0", "ax + b = 0, where a ≠ 0", "ax³ + bx² + c = 0, where a ≠ 0"], "A quadratic has degree exactly 2, so the coefficient of x² must be non-zero."],
    ["easy", "The roots of x² − 7x = 0 are:", "0 and 7", ["7 only", "0 and −7", "−7 and 7"], "x(x − 7) = 0 gives x = 0 or x = 7."],
    ["easy", "If the discriminant of a quadratic equation is positive, its roots are:", "Real and distinct", ["Real and equal", "Not real", "Always zero"], "D > 0 gives two different real values from x = [−b ± √D]/2a."],
    ["easy", "Which of the following is a root of x² + x − 6 = 0?", "2", ["−2", "3", "1"], "2² + 2 − 6 = 0; the roots are 2 and −3."],
    ["medium", "The roots of 2x² − 5x + 3 = 0 are:", "3/2 and 1", ["−3/2 and −1", "3 and 1/2", "5/2 and 3/2"], "2x² − 2x − 3x + 3 = (2x − 3)(x − 1) = 0, so x = 3/2 or 1."],
    ["medium", "The positive value of k for which x² + kx + 9 = 0 has equal roots is:", "6", ["3", "9", "36"], "Equal roots need D = k² − 36 = 0, so k = 6."],
    ["medium", "The roots of 3x² − 4√3x + 4 = 0 are:", "Real and equal", ["Real and distinct", "Not real", "One positive and one negative"], "D = (4√3)² − 4 × 3 × 4 = 48 − 48 = 0."],
    ["medium", "Using the quadratic formula, the roots of x² − 2x − 4 = 0 are:", "1 ± √5", ["−1 ± √5", "1 ± √3", "2 ± √5"], "x = [2 ± √(4 + 16)]/2 = (2 ± 2√5)/2 = 1 ± √5."],
    ["medium", "If x is the smaller of two consecutive odd positive integers whose product is 63, the equation satisfied by x is:", "x² + 2x − 63 = 0", ["x² + x − 63 = 0", "x² + 2x + 63 = 0", "x² − 2x − 63 = 0"], "The integers are x and x + 2, so x(x + 2) = 63."],
    ["hard", "A rectangular field has area 528 m², and its length is 1 m more than twice its breadth. Its breadth is:", "16 m", ["33 m", "22 m", "12 m"], "b(2b + 1) = 528 gives 2b² + b − 528 = 0; b = (−1 + 65)/4 = 16 m (and 16 × 33 = 528)."],
    ["hard", "Assertion (A): The equation 2x² − 3x + 5 = 0 has two distinct real roots. Reason (R): A quadratic equation has two distinct real roots when b² − 4ac > 0.", "A is false, but R is true", ["Both A and R are true, and R is the correct explanation of A", "Both A and R are true, but R is not the correct explanation of A", "A is true, but R is false"], "D = 9 − 40 = −31 < 0, so there are no real roots; R is the correct condition."],
    ["hard", "The non-zero value of k for which kx(x − 2) + 6 = 0 has two equal roots is:", "6", ["3", "−6", "12"], "kx² − 2kx + 6 = 0 has D = 4k² − 24k = 4k(k − 6) = 0, so k = 6."],
  ],
  "m10-ap": [
    ["easy", "The common difference of the AP 10, 6, 2, −2, … is:", "−4", ["4", "−2", "−8"], "d = 6 − 10 = −4."],
    ["easy", "The first term and common difference of the AP 3/2, 1/2, −1/2, … are:", "a = 3/2, d = −1", ["a = 3/2, d = 1", "a = 1/2, d = −1", "a = 3/2, d = −1/2"], "a = 3/2 and d = 1/2 − 3/2 = −1."],
    ["easy", "The 6th term of the AP −3, 1, 5, … is:", "17", ["21", "13", "20"], "a₆ = −3 + 5 × 4 = 17."],
    ["easy", "The common difference of the AP whose nth term is aₙ = 3 + 4n is:", "4", ["3", "7", "4n"], "aₙ₊₁ − aₙ = 4(n + 1) − 4n = 4."],
    ["medium", "The next term of the AP √2, √8, √18, … is:", "√32", ["√24", "√28", "√36"], "The terms are √2, 2√2, 3√2, so the next is 4√2 = √32."],
    ["medium", "If k + 2, 4k − 6 and 3k − 2 are three consecutive terms of an AP, then k is:", "3", ["2", "4", "−3"], "2(4k − 6) = (k + 2) + (3k − 2) gives 8k − 12 = 4k, so k = 3 (terms 5, 6, 7)."],
    ["medium", "How many two-digit numbers are divisible by 3?", "30", ["33", "29", "31"], "12, 15, …, 99: 99 = 12 + (n − 1) × 3 gives n = 30."],
    ["medium", "The sum of the first 12 terms of the AP 5, 9, 13, … is:", "324", ["300", "348", "49"], "S₁₂ = 12/2 [2 × 5 + 11 × 4] = 6 × 54 = 324."],
    ["medium", "The 10th term from the end of the AP 4, 9, 14, …, 254 is:", "209", ["204", "214", "49"], "Counting back from 254 with difference 5: 254 − 9 × 5 = 209."],
    ["hard", "If the sum of the first n terms of an AP is Sₙ = 3n² + 5n, its common difference is:", "6", ["3", "8", "5"], "aₙ = Sₙ − Sₙ₋₁ = 6n + 2, so a₁ = 8, a₂ = 14 and d = 6."],
    ["hard", "Ravi saves ₹500 in the first month and increases his saving by ₹100 every month. His total saving in the first year is:", "₹12600", ["₹1600", "₹13200", "₹12000"], "S₁₂ = 12/2 [2 × 500 + 11 × 100] = 6 × 2100 = ₹12600."],
    ["hard", "Assertion (A): 0 is a term of the AP 31, 28, 25, … . Reason (R): A number is a term of an AP only if setting aₙ equal to it gives a natural number n.", "A is false, but R is true", ["Both A and R are true, and R is the correct explanation of A", "Both A and R are true, but R is not the correct explanation of A", "A is true, but R is false"], "31 + (n − 1)(−3) = 0 gives n = 34/3, which is not a natural number, so 0 is not a term."],
  ],
  "m10-coord": [
    ["easy", "The distance between (2, 3) and (2, 7) is:", "4", ["10", "5", "16"], "√[(2 − 2)² + (7 − 3)²] = √16 = 4."],
    ["easy", "The midpoint of the segment joining (−3, 5) and (7, −1) is:", "(2, 2)", ["(5, −3)", "(4, 4)", "(2, 3)"], "((−3 + 7)/2, (5 − 1)/2) = (2, 2)."],
    ["easy", "The distance between (a, b) and (−a, −b) is:", "2√(a² + b²)", ["√(a² + b²)", "2(a + b)", "0"], "√[(2a)² + (2b)²] = √(4a² + 4b²) = 2√(a² + b²)."],
    ["easy", "If the midpoint of AB is the origin and A is (3, −5), then B is:", "(−3, 5)", ["(3, 5)", "(−3, −5)", "(6, −10)"], "(3 + x)/2 = 0 and (−5 + y)/2 = 0 give B = (−3, 5)."],
    ["medium", "The point dividing the join of (−1, 7) and (4, −3) internally in the ratio 2 : 3 is:", "(1, 3)", ["(2, 1)", "(1.5, 2)", "(3, −1)"], "x = (2 × 4 + 3 × (−1))/5 = 1 and y = (2 × (−3) + 3 × 7)/5 = 3."],
    ["medium", "The values of x for which the distance between P(x, 3) and Q(5, 7) is 5 units are:", "8 and 2", ["8 and −2", "2 and −8", "5 and 3"], "(x − 5)² + 16 = 25 gives x − 5 = ±3, so x = 8 or 2."],
    ["medium", "The ratio in which the x-axis divides the segment joining (2, −3) and (5, 6) is:", "1 : 2", ["2 : 1", "1 : 3", "3 : 1"], "For ratio k : 1, y = (6k − 3)/(k + 1) = 0 gives k = 1/2, i.e., 1 : 2."],
    ["medium", "The point on the y-axis equidistant from (−5, 2) and (3, −2) is:", "(0, 2)", ["(0, −2)", "(2, 0)", "(0, 4)"], "25 + (y − 2)² = 9 + (y + 2)² gives 16 = 8y, so y = 2; both distances are 5."],
    ["medium", "In a classroom seating grid, Riya sits at (2, 1) and Aman at (6, 4). The distance between them is:", "5 units", ["7 units", "25 units", "4 units"], "√[(6 − 2)² + (4 − 1)²] = √(16 + 9) = 5 units."],
    ["hard", "A(1, 2), B(4, y), C(x, 6) and D(3, 5) are the vertices of parallelogram ABCD taken in order. Then (x, y) is:", "(6, 3)", ["(3, 6)", "(5, 3)", "(6, 4)"], "Diagonals bisect each other: ((1 + x)/2, 4) = (7/2, (5 + y)/2), so x = 6 and y = 3."],
    ["hard", "The point of trisection of the segment joining (4, −1) and (−2, −3) that is nearer to (4, −1) is:", "(2, −5/3)", ["(0, −7/3)", "(1, −2)", "(2, −7/3)"], "Ratio 1 : 2 gives x = (−2 + 8)/3 = 2 and y = (−3 − 2)/3 = −5/3."],
    ["hard", "Assertion (A): The points A(−1, 0), B(3, 1), C(2, 2) and D(−2, 1), taken in order, form a parallelogram. Reason (R): The diagonals of a parallelogram bisect each other.", "Both A and R are true, and R is the correct explanation of A", ["Both A and R are true, but R is not the correct explanation of A", "A is true, but R is false", "A is false, but R is true"], "Midpoint of AC = (1/2, 1) = midpoint of BD, so the diagonals bisect each other and ABCD is a parallelogram."],
  ],
  "m10-triangles": [
    ["easy", "Which triangles are always similar to each other?", "All equilateral triangles", ["All isosceles triangles", "All scalene triangles", "All right-angled triangles"], "Every equilateral triangle has angles 60°, 60°, 60°, so any two are similar by AA."],
    ["easy", "Two polygons with the same number of sides are similar if their corresponding angles are equal and their corresponding sides are:", "In the same ratio", ["Equal in length", "Parallel", "Perpendicular"], "Similarity needs equal angles and proportional sides."],
    ["easy", "If △ABC ~ △DEF, then ∠B corresponds to:", "∠E", ["∠D", "∠F", "∠A"], "The order of letters gives A ↔ D, B ↔ E, C ↔ F."],
    ["easy", "In △ABC, DE ∥ BC with D on AB and E on AC. If AD/DB = 3/5, then AE/EC is:", "3/5", ["5/3", "3/8", "5/8"], "By BPT, AD/DB = AE/EC."],
    ["medium", "In △ABC, D and E lie on AB and AC with AD = 1.5 cm, DB = 3 cm, AE = 1 cm and EC = 2 cm. Then:", "DE ∥ BC", ["DE ⟂ BC", "DE = BC", "DE = ½ BC"], "AD/DB = AE/EC = 1/2, so by the converse of BPT, DE ∥ BC."],
    ["medium", "△ABC ~ △DEF with AB = 3 cm, BC = 4 cm, CA = 5 cm and DE = 6 cm. The perimeter of △DEF is:", "24 cm", ["12 cm", "18 cm", "36 cm"], "The scale factor is 6/3 = 2, so the sides are 6, 8, 10 and the perimeter is 24 cm."],
    ["medium", "In △ABC, DE ∥ BC with AD = x, DB = x − 2, AE = x + 2 and EC = x − 1. The value of x is:", "4", ["2", "3", "6"], "x/(x − 2) = (x + 2)/(x − 1) gives x² − x = x² − 4, so x = 4."],
    ["medium", "A 6 m pole casts a 4 m shadow. At the same time, a tower casts a 28 m shadow. The height of the tower is:", "42 m", ["18⅔ m", "36 m", "48 m"], "The triangles are similar (AA), so h/28 = 6/4 and h = 42 m."],
    ["medium", "In △ABC and △PQR, AB/QR = BC/RP = CA/PQ. Then:", "△ABC ~ △QRP", ["△ABC ~ △PQR", "△ABC ~ △RQP", "△ABC ~ △PRQ"], "AB ↔ QR, BC ↔ RP, CA ↔ PQ give A ↔ Q, B ↔ R, C ↔ P (SSS similarity)."],
    ["hard", "ABCD is a trapezium with AB ∥ DC, and its diagonals meet at O. If AB = 2 CD and OC = 3 cm, then OA is:", "6 cm", ["1.5 cm", "3 cm", "9 cm"], "△AOB ~ △COD (AA), so OA/OC = AB/CD = 2 and OA = 6 cm."],
    ["hard", "A girl 1.6 m tall stands 4 m from the foot of a lamp post with the lamp 4.8 m above the ground. The length of her shadow is:", "2 m", ["1⅓ m", "4 m", "3 m"], "By similar triangles, 1.6/s = 4.8/(4 + s), so 4.8s = 6.4 + 1.6s and s = 2 m."],
    ["hard", "Assertion (A): Any two right-angled triangles are similar. Reason (R): Two triangles are similar if two angles of one are equal to two angles of the other.", "A is false, but R is true", ["Both A and R are true, and R is the correct explanation of A", "Both A and R are true, but R is not the correct explanation of A", "A is true, but R is false"], "Two right triangles share only the 90° angle in general (e.g., 30-60-90 and 45-45-90), so A is false; R is the AA criterion."],
  ],
  "m10-circles": [
    ["easy", "The common point of a tangent and a circle is called the:", "Point of contact", ["Centre", "End of a diameter", "Vertex"], "A tangent meets the circle at exactly one point, the point of contact."],
    ["easy", "How many tangents can be drawn to a circle from a point inside it?", "0", ["1", "2", "Infinitely many"], "Every line through an interior point cuts the circle at two points, so none is a tangent."],
    ["easy", "How many tangents can a circle have parallel to a given secant?", "2", ["1", "0", "Infinitely many"], "Exactly two tangents, at the ends of the diameter perpendicular to the secant, are parallel to it."],
    ["easy", "How many tangents can a circle have in all?", "Infinitely many", ["1", "2", "4"], "There is one tangent at each of the infinitely many points of the circle."],
    ["medium", "The length of the tangent from a point Q to a circle is 24 cm and Q is 25 cm from the centre. The radius is:", "7 cm", ["1 cm", "12.5 cm", "√1201 cm"], "Tangent ⟂ radius, so r = √(25² − 24²) = √49 = 7 cm."],
    ["medium", "PA and PB are tangents from P to a circle with ∠APB = 60° and PA = 8 cm. The length of chord AB is:", "8 cm", ["4 cm", "8√3 cm", "16 cm"], "PA = PB, so △PAB is isosceles with apex 60°, hence equilateral and AB = 8 cm."],
    ["medium", "Two concentric circles have radii 5 cm and 3 cm. The length of the chord of the larger circle that touches the smaller circle is:", "8 cm", ["4 cm", "2√34 cm", "6 cm"], "The radius of the smaller circle is ⟂ to the chord, so half-chord = √(25 − 9) = 4 cm and the chord is 8 cm."],
    ["medium", "PA and PB are tangents from P to a circle with centre O. If ∠AOB = 110°, then ∠APB is:", "70°", ["110°", "55°", "35°"], "∠OAP = ∠OBP = 90°, so ∠APB = 360° − 180° − 110° = 70°."],
    ["medium", "A quadrilateral ABCD is drawn to circumscribe a circle. If AB = 6 cm, BC = 7 cm and CD = 4 cm, then AD is:", "3 cm", ["5 cm", "9 cm", "1 cm"], "Equal tangents give AB + CD = BC + AD, so 10 = 7 + AD and AD = 3 cm."],
    ["hard", "PA and PB are tangents from P to a circle with centre O, inclined to each other at 70°. Then ∠POA is:", "55°", ["35°", "70°", "110°"], "OP bisects ∠APB, so ∠APO = 35°; in right △OAP, ∠POA = 90° − 35° = 55°."],
    ["hard", "A circle is inscribed in △ABC, touching AB, BC and CA at P, Q and R. If AB = 10 cm, BC = 8 cm and CA = 12 cm, then AP is:", "7 cm", ["5 cm", "3 cm", "6 cm"], "With AP = AR = x, BP = BQ = y, CQ = CR = z: x + y = 10, y + z = 8, z + x = 12, so x + y + z = 15 and x = 15 − 8 = 7 cm."],
    ["hard", "Assertion (A): The tangents drawn at the ends of a diameter of a circle are parallel. Reason (R): The tangent at any point of a circle is perpendicular to the radius through the point of contact.", "Both A and R are true, and R is the correct explanation of A", ["Both A and R are true, but R is not the correct explanation of A", "A is true, but R is false", "A is false, but R is true"], "By R both tangents are ⟂ to the same diameter, so they are parallel."],
  ],
  "m10-trig": [
    ["easy", "cosec θ is the reciprocal of:", "sin θ", ["cos θ", "tan θ", "sec θ"], "cosec θ = 1/sin θ = hypotenuse/opposite."],
    ["easy", "The value of tan 60° is:", "√3", ["1/√3", "1", "√3/2"], "tan 60° = sin 60°/cos 60° = (√3/2)/(1/2) = √3."],
    ["easy", "The value of cos 90° is:", "0", ["1", "Not defined", "1/2"], "Standard value: cos 90° = 0."],
    ["easy", "In △ABC, right-angled at B, AB = 5 cm, BC = 12 cm and AC = 13 cm. Then sin A is:", "12/13", ["5/13", "12/5", "13/12"], "sin A = opposite/hypotenuse = BC/AC = 12/13."],
    ["medium", "If sec θ = 13/12 (θ acute), then sin θ is:", "5/13", ["12/13", "5/12", "13/5"], "cos θ = 12/13, so the sides are 12, 5, 13 and sin θ = 5/13."],
    ["medium", "The value of 2 tan²45° + cos²30° − sin²60° is:", "2", ["1", "3", "5/2"], "2(1) + 3/4 − 3/4 = 2."],
    ["medium", "The value of (1 − tan²45°)/(1 + tan²45°) is:", "0", ["1", "2", "1/2"], "tan 45° = 1, so (1 − 1)/(1 + 1) = 0."],
    ["medium", "cosec²θ − cot²θ equals:", "1", ["0", "−1", "2"], "Dividing sin²θ + cos²θ = 1 by sin²θ gives 1 + cot²θ = cosec²θ."],
    ["medium", "If √3 tan θ = 1 and θ is acute, then θ is:", "30°", ["60°", "45°", "90°"], "tan θ = 1/√3, so θ = 30°."],
    ["hard", "If sin(A + B) = 1 and cos(A − B) = √3/2, where A > B and A + B ≤ 90°, then:", "A = 60°, B = 30°", ["A = 30°, B = 60°", "A = 45°, B = 45°", "A = 75°, B = 15°"], "A + B = 90° and A − B = 30°, so A = 60° and B = 30°."],
    ["hard", "The value of (1 + tan²θ)(1 − sin θ)(1 + sin θ) is:", "1", ["sec²θ", "cos²θ", "tan²θ"], "(1 + tan²θ)(1 − sin²θ) = sec²θ × cos²θ = 1."],
    ["hard", "Assertion (A): sin θ = 4/3 for some acute angle θ. Reason (R): sin θ = opposite/hypotenuse, and the hypotenuse is the longest side of a right triangle.", "A is false, but R is true", ["Both A and R are true, and R is the correct explanation of A", "Both A and R are true, but R is not the correct explanation of A", "A is true, but R is false"], "By R, sin θ < 1 for an acute angle, so sin θ cannot be 4/3."],
  ],
  "m10-heights": [
    ["easy", "When the Sun's elevation is 60°, a vertical pole of height h casts a shadow of length:", "h/√3", ["h√3", "h", "2h"], "tan 60° = h/shadow, so shadow = h/√3."],
    ["easy", "The angle of elevation of the top of a tower from a point P and the angle of depression of P from the top of the tower are:", "Equal", ["Complementary", "Supplementary", "Always 45°"], "They are alternate angles between the horizontal at the top and the ground, which are parallel."],
    ["easy", "A kite is flying on a 100 m string that makes 30° with the ground. Assuming the string is straight, the height of the kite is:", "50 m", ["50√3 m", "100 m", "200 m"], "h = 100 × sin 30° = 100 × 1/2 = 50 m."],
    ["easy", "A tree 12 m high casts a shadow 12√3 m long. The angle of elevation of the Sun is:", "30°", ["60°", "45°", "90°"], "tan θ = 12/(12√3) = 1/√3, so θ = 30°."],
    ["medium", "From the top of a 75 m high lighthouse, the angle of depression of a ship is 30°. The distance of the ship from the foot of the lighthouse is:", "75√3 m", ["25√3 m", "75 m", "150 m"], "tan 30° = 75/d, so d = 75√3 m."],
    ["medium", "A kite is 60 m above the ground and its string makes 60° with the ground. The length of the string is:", "40√3 m", ["30√3 m", "120 m", "20√3 m"], "sin 60° = 60/l, so l = 120/√3 = 40√3 m."],
    ["medium", "A tree breaks due to wind and its top touches the ground 8 m from the foot, making 30° with the ground. The original height of the tree is:", "8√3 m", ["8/√3 m", "16 m", "16√3 m"], "Standing part = 8 tan 30° = 8/√3 and broken part = 8/cos 30° = 16/√3; total = 24/√3 = 8√3 m."],
    ["medium", "A 1.5 m tall boy stands 28.5 m from a 30 m tall building. The angle of elevation of the top of the building from his eyes is:", "45°", ["30°", "60°", "90°"], "tan θ = (30 − 1.5)/28.5 = 1, so θ = 45°."],
    ["medium", "A wheelchair ramp rises to a height of 1 m and is inclined at 30° to the ground. The length of the ramp is:", "2 m", ["1 m", "√3 m", "2/√3 m"], "sin 30° = 1/l, so l = 2 m."],
    ["hard", "From the top of a 50 m cliff, the angles of depression of two boats on the same side, in line with the cliff, are 45° and 30°. The distance between the boats is:", "50(√3 − 1) m", ["50(√3 + 1) m", "50√3 m", "50 m"], "The boats are 50/tan 45° = 50 m and 50/tan 30° = 50√3 m away, so they are 50√3 − 50 m apart."],
    ["hard", "From a point on the ground, the angles of elevation of the bottom and top of a 10 m flagstaff on a building are 30° and 45°. The height of the building is:", "5(√3 + 1) m", ["5(√3 − 1) m", "10√3 m", "10(√3 + 1) m"], "tan 45° gives d = h + 10, and tan 30° gives h = (h + 10)/√3, so h = 10/(√3 − 1) = 5(√3 + 1) m."],
    ["hard", "Assertion (A): If the shadow of a pole is √3 times its height, the angle of elevation of the Sun is 30°. Reason (R): tan θ = height of the pole ÷ length of its shadow.", "Both A and R are true, and R is the correct explanation of A", ["Both A and R are true, but R is not the correct explanation of A", "A is true, but R is false", "A is false, but R is true"], "By R, tan θ = h/(√3h) = 1/√3, so θ = 30°."],
  ],
  "m10-areas": [
    ["easy", "The length of an arc of angle θ in a circle of radius r is:", "(θ/360°) × 2πr", ["(θ/360°) × πr²", "θ × 2πr", "2πr/θ"], "An arc is the fraction θ/360° of the full circumference 2πr."],
    ["easy", "The central angle of a sector that is one-sixth of a circle is:", "60°", ["30°", "90°", "120°"], "360° ÷ 6 = 60°."],
    ["easy", "The area of a sector of angle 60° in a circle of radius 6 cm is:", "6π cm²", ["2π cm²", "12π cm²", "36π cm²"], "(60/360) × π × 36 = 6π cm²."],
    ["easy", "The arc length of a sector of angle 180° in a circle of radius 14 cm (π = 22/7) is:", "44 cm", ["88 cm", "22 cm", "308 cm"], "(180/360) × 2 × (22/7) × 14 = 44 cm."],
    ["medium", "The area of a sector of angle 120° in a circle of radius 21 cm (π = 22/7) is:", "462 cm²", ["44 cm²", "924 cm²", "1386 cm²"], "(120/360) × (22/7) × 441 = (1/3) × 1386 = 462 cm²."],
    ["medium", "A sector of a circle of radius 10 cm has an arc of length 22 cm. Its area is:", "110 cm²", ["220 cm²", "55 cm²", "32 cm²"], "Area of sector = ½ × arc length × radius = ½ × 22 × 10 = 110 cm²."],
    ["medium", "The minute hand of a clock is 21 cm long. The distance its tip travels in 20 minutes (π = 22/7) is:", "44 cm", ["22 cm", "462 cm", "132 cm"], "20 minutes = 120°, so arc = (120/360) × 2 × (22/7) × 21 = 44 cm."],
    ["medium", "A chord of a circle of radius 10 cm subtends a right angle at the centre. The area of the minor segment (π = 3.14) is:", "28.5 cm²", ["78.5 cm²", "128.5 cm²", "50 cm²"], "Sector = ¼ × 3.14 × 100 = 78.5 cm² and triangle = ½ × 10 × 10 = 50 cm²; segment = 28.5 cm²."],
    ["medium", "The area of a sector of angle 45° in a circle of radius 14 cm (π = 22/7) is:", "77 cm²", ["11 cm²", "154 cm²", "616 cm²"], "(45/360) × (22/7) × 196 = (1/8) × 616 = 77 cm²."],
    ["hard", "A chord of a circle of radius 12 cm subtends 60° at the centre. The area of the minor segment (π = 3.14, √3 = 1.73) is:", "13.08 cm²", ["75.36 cm²", "137.64 cm²", "62.28 cm²"], "Sector = (1/6) × 3.14 × 144 = 75.36 cm², equilateral triangle = (√3/4) × 144 = 62.28 cm²; difference = 13.08 cm²."],
    ["hard", "A horse is tied to a corner of a square field of side 15 m with a rope. If the rope is lengthened from 5 m to 10 m, the increase in grazing area (π = 3.14) is:", "58.875 m²", ["19.625 m²", "78.5 m²", "235.5 m²"], "The horse grazes a quadrant: ¼ × 3.14 × (10² − 5²) = ¼ × 3.14 × 75 = 58.875 m²."],
    ["hard", "Assertion (A): The length of an arc of 30° in a circle of radius 42 cm is 22 cm (π = 22/7). Reason (R): Length of an arc of angle θ = (θ/360°) × πr².", "A is true, but R is false", ["Both A and R are true, and R is the correct explanation of A", "Both A and R are true, but R is not the correct explanation of A", "A is false, but R is true"], "(30/360) × 2 × (22/7) × 42 = 264/12 = 22 cm, so A is true; R gives the sector area, not the arc length."],
  ],
  "m10-surface": [
    ["easy", "The total surface area of a solid hemisphere of radius r is:", "3πr²", ["2πr²", "4πr²", "πr²"], "Curved surface 2πr² plus the flat circular base πr²."],
    ["easy", "A capsule is a cylinder with a hemisphere at each end. Its outer surface area is:", "CSA of cylinder + 2 × CSA of hemisphere", ["TSA of cylinder + 2 × CSA of hemisphere", "Volume of cylinder + volume of sphere", "CSA of cylinder only"], "The flat ends of the cylinder are covered by the hemispheres, so only curved surfaces are exposed."],
    ["easy", "The slant height of a cone with radius 3 cm and height 4 cm is:", "5 cm", ["7 cm", "√7 cm", "25 cm"], "l = √(r² + h²) = √(9 + 16) = 5 cm."],
    ["easy", "The volume of a hemisphere of radius r is:", "⅔ πr³", ["4/3 πr³", "2πr²", "⅓ πr³"], "Half of the sphere's volume 4/3 πr³."],
    ["medium", "A solid is a hemisphere of radius 3 cm on top of a cylinder of radius 3 cm and height 10 cm. Its volume is:", "108π cm³", ["90π cm³", "126π cm³", "72π cm³"], "Cylinder π × 9 × 10 = 90π and hemisphere ⅔ × π × 27 = 18π; total 108π cm³."],
    ["medium", "A cone and a cylinder have the same base radius and height. The ratio of their volumes (cone : cylinder) is:", "1 : 3", ["3 : 1", "1 : 2", "2 : 3"], "⅓πr²h : πr²h = 1 : 3."],
    ["medium", "A cone of the same base and height is removed from a solid cylinder of radius 7 cm and height 6 cm. The remaining volume (π = 22/7) is:", "616 cm³", ["924 cm³", "308 cm³", "1232 cm³"], "Cylinder = 22/7 × 49 × 6 = 924 cm³ and cone = 308 cm³; 924 − 308 = 616 cm³."],
    ["medium", "A tent is a cylinder of radius 2 m and height 3 m topped by a cone of the same radius and height 1.5 m. The canvas needed (no floor) is:", "17π m²", ["12π m²", "5π m²", "21π m²"], "Cone l = √(4 + 2.25) = 2.5 m; canvas = 2π(2)(3) + π(2)(2.5) = 12π + 5π = 17π m²."],
    ["medium", "A medicine capsule is a cylinder with hemispherical ends, total length 14 mm and diameter 5 mm. Its surface area (π = 22/7) is:", "220 mm²", ["110 mm²", "440 mm²", "198 mm²"], "r = 2.5 mm, cylinder length = 14 − 5 = 9 mm; area = 2π(2.5)(9) + 4π(2.5)² = 45π + 25π = 70π = 220 mm²."],
    ["hard", "A toy is a cone of radius 3.5 cm on a hemisphere of the same radius, with total height 15.5 cm. Its total surface area (π = 22/7) is:", "214.5 cm²", ["137.5 cm²", "253 cm²", "291.5 cm²"], "Cone height 12 cm, l = 12.5 cm; πrl = 137.5 cm² and 2πr² = 77 cm²; total 214.5 cm²."],
    ["hard", "A hemisphere is scooped out from each end of a solid cylinder of height 10 cm and radius 3.5 cm. The total surface area of the article (π = 22/7) is:", "374 cm²", ["220 cm²", "297 cm²", "451 cm²"], "CSA of cylinder = 2 × (22/7) × 3.5 × 10 = 220 cm², two hemispherical hollows = 2 × 2 × (22/7) × 12.25 = 154 cm²; total 374 cm²."],
    ["hard", "Assertion (A): The volume of a solid made by placing a hemisphere on a cylinder of the same radius is the sum of their volumes. Reason (R): The volume of a hemisphere of radius r is ⅔ πr³.", "Both A and R are true, but R is not the correct explanation of A", ["Both A and R are true, and R is the correct explanation of A", "A is true, but R is false", "A is false, but R is true"], "Volumes of joined solids add, so A is true; R is a true formula but does not explain why volumes add."],
  ],
  "m10-stats": [
    ["easy", "In the step-deviation method for the mean, uᵢ is:", "(xᵢ − a)/h", ["(xᵢ + a)/h", "xᵢ − a", "h(xᵢ − a)"], "Each deviation from the assumed mean a is divided by the class width h."],
    ["easy", "By the direct method, the mean of grouped data is:", "Σfᵢxᵢ / Σfᵢ", ["Σfᵢ / Σxᵢ", "Σxᵢ / Σfᵢ", "Σfᵢxᵢ × Σfᵢ"], "Multiply each class mark by its frequency, add, and divide by the total frequency."],
    ["easy", "For the classes 0–10, 10–20 and 20–30 with frequencies 5, 8 and 3, the modal class is:", "10–20", ["0–10", "20–30", "10–30"], "The modal class has the highest frequency, 8."],
    ["easy", "In a cumulative frequency table, the cumulative frequency of the last class equals:", "The total frequency n", ["The frequency of the last class", "Zero", "The class width"], "Cumulative frequency keeps adding all frequencies up to the last class."],
    ["medium", "The mean of the data with xᵢ = 10, 20, 30 and fᵢ = 3, 5, 2 is:", "19", ["20", "19.5", "190"], "Σfᵢxᵢ = 30 + 100 + 60 = 190 and Σfᵢ = 10, so the mean is 19."],
    ["medium", "For classes 0–10, 10–20, 20–30, 30–40, 40–50 with frequencies 5, 8, 12, 6, 4, the mode is:", "24", ["25", "22", "28"], "Modal class 20–30: 20 + [(12 − 8)/(24 − 8 − 6)] × 10 = 20 + 4 = 24."],
    ["medium", "For classes 0–10, 10–20, 20–30, 30–40, 40–50 with frequencies 5, 10, 20, 10, 5, the median is:", "25", ["20", "30", "22.5"], "n/2 = 25, median class 20–30 with cf = 15: 20 + [(25 − 15)/20] × 10 = 25."],
    ["medium", "If the mode of a distribution is 24 and its mean is 21, then by the empirical relation the median is:", "22", ["23", "22.5", "45"], "3 Median = Mode + 2 Mean = 24 + 42 = 66, so Median = 22."],
    ["medium", "Using the assumed-mean method with a = 25, Σfᵢdᵢ = 40 and Σfᵢ = 20, the mean is:", "27", ["23", "25", "65"], "Mean = a + Σfᵢdᵢ/Σfᵢ = 25 + 40/20 = 27."],
    ["hard", "In the step-deviation method, a = 45, h = 10, Σfᵢuᵢ = −6 and Σfᵢ = 30. The mean is:", "43", ["47", "44.8", "39"], "Mean = 45 + 10 × (−6/30) = 45 − 2 = 43."],
    ["hard", "The classes 0–10, 10–20, 20–30, 30–40, 40–50 have frequencies 5, 10, f, 8, 2 and the mean is 23. The value of f is:", "15", ["10", "12", "20"], "Σfᵢxᵢ = 545 + 25f and Σfᵢ = 25 + f; 545 + 25f = 23(25 + f) gives 2f = 30, so f = 15."],
    ["hard", "Assertion (A): For the classes 10–20, 20–30, 30–40 with frequencies 4, 9, 7, the modal class is 20–30. Reason (R): The modal class is the class with the highest cumulative frequency.", "A is true, but R is false", ["Both A and R are true, and R is the correct explanation of A", "Both A and R are true, but R is not the correct explanation of A", "A is false, but R is true"], "20–30 has the highest frequency (9), so A is true; the modal class uses frequency, not cumulative frequency."],
  ],
  "m10-prob": [
    ["easy", "Which of the following cannot be the probability of an event?", "1.5", ["0", "2/3", "0.7"], "Probability always lies between 0 and 1."],
    ["easy", "A die is thrown once. The probability of getting a number greater than 4 is:", "1/3", ["1/2", "2/3", "1/6"], "Favourable outcomes are 5 and 6: 2/6 = 1/3."],
    ["easy", "The sum of the probabilities of all the elementary events of an experiment is:", "1", ["0", "1/2", "Equal to the number of outcomes"], "Together the elementary events cover every possible outcome."],
    ["medium", "A card is drawn from a well-shuffled deck of 52 cards. The probability that it is a red face card is:", "3/26", ["3/13", "1/2", "1/26"], "There are 6 red face cards (J, Q, K of hearts and diamonds): 6/52 = 3/26."],
    ["medium", "A letter is chosen at random from the word MATHEMATICS. The probability that it is a vowel is:", "4/11", ["7/11", "3/11", "1/4"], "11 letters, of which A, E, A, I are vowels: 4/11."],
    ["medium", "Two dice are thrown together. The probability that the sum of the numbers is 10 is:", "1/12", ["1/6", "1/18", "5/36"], "Favourable pairs (4, 6), (5, 5), (6, 4): 3/36 = 1/12."],
    ["medium", "A box has 90 discs numbered 1 to 90. The probability that a disc drawn at random bears a perfect square is:", "1/10", ["1/9", "9/100", "1/90"], "Perfect squares 1, 4, …, 81 are 9 in number: 9/90 = 1/10."],
    ["medium", "A lot of 400 bulbs contains 20 defective ones. The probability that a bulb chosen at random is not defective is:", "19/20", ["1/20", "1/19", "9/10"], "380 good bulbs out of 400: 380/400 = 19/20."],
    ["hard", "Three coins are tossed together. The probability of getting at least two heads is:", "1/2", ["3/8", "1/8", "7/8"], "HHH, HHT, HTH, THH are favourable: 4/8 = 1/2."],
    ["hard", "Two dice are thrown together. The probability that the product of the numbers is even is:", "3/4", ["1/2", "1/4", "1/3"], "The product is odd only when both are odd (9 of 36 cases), so P = 1 − 9/36 = 3/4."],
    ["hard", "Assertion (A): The probability that a leap year chosen at random has 53 Sundays is 2/7. Reason (R): A leap year has 366 days, that is, 52 weeks and 2 extra days.", "Both A and R are true, and R is the correct explanation of A", ["Both A and R are true, but R is not the correct explanation of A", "A is true, but R is false", "A is false, but R is true"], "The 2 extra days form one of 7 equally likely consecutive pairs, and 2 of these (Sat–Sun, Sun–Mon) include a Sunday."],
  ],
};
