import type { ChapterDef } from "@/lib/neet/types";

export const NEET_CHAPTERS: ChapterDef[] = [
  { id: "phy-units", subject: "physics", classLevel: 11, name: "Units and Measurements", unit: "Mechanics", audience: "neet" },
  { id: "phy-straight", subject: "physics", classLevel: 11, name: "Motion in a Straight Line", unit: "Mechanics", audience: "neet" },
  { id: "phy-plane", subject: "physics", classLevel: 11, name: "Motion in a Plane", unit: "Mechanics", audience: "neet" },
  { id: "phy-laws", subject: "physics", classLevel: 11, name: "Laws of Motion", unit: "Mechanics", audience: "neet" },
  { id: "phy-work", subject: "physics", classLevel: 11, name: "Work, Energy and Power", unit: "Mechanics", audience: "neet" },
  { id: "phy-rotation", subject: "physics", classLevel: 11, name: "System of Particles & Rotation", unit: "Mechanics", audience: "neet" },
  { id: "phy-gravitation", subject: "physics", classLevel: 11, name: "Gravitation", unit: "Mechanics", audience: "neet" },
  { id: "phy-solids", subject: "physics", classLevel: 11, name: "Mechanical Properties of Solids", unit: "Properties of Matter", audience: "neet" },
  { id: "phy-fluids", subject: "physics", classLevel: 11, name: "Mechanical Properties of Fluids", unit: "Properties of Matter", audience: "neet" },
  { id: "phy-thermal", subject: "physics", classLevel: 11, name: "Thermal Properties of Matter", unit: "Heat & Thermo", audience: "neet" },
  { id: "phy-thermo", subject: "physics", classLevel: 11, name: "Thermodynamics", unit: "Heat & Thermo", audience: "neet" },
  { id: "phy-kinetic", subject: "physics", classLevel: 11, name: "Kinetic Theory", unit: "Heat & Thermo", audience: "neet" },
  { id: "phy-oscillations", subject: "physics", classLevel: 11, name: "Oscillations", unit: "Waves", audience: "neet" },
  { id: "phy-waves", subject: "physics", classLevel: 11, name: "Waves", unit: "Waves", audience: "neet" },
  { id: "phy-charges", subject: "physics", classLevel: 12, name: "Electric Charges and Fields", unit: "Electrostatics", audience: "neet" },
  { id: "phy-potential", subject: "physics", classLevel: 12, name: "Electrostatic Potential & Capacitance", unit: "Electrostatics", audience: "neet" },
  { id: "phy-current", subject: "physics", classLevel: 12, name: "Current Electricity", unit: "Current Electricity", audience: "neet" },
  { id: "phy-moving", subject: "physics", classLevel: 12, name: "Moving Charges and Magnetism", unit: "Magnetism", audience: "neet" },
  { id: "phy-magnetism", subject: "physics", classLevel: 12, name: "Magnetism and Matter", unit: "Magnetism", audience: "neet" },
  { id: "phy-emi", subject: "physics", classLevel: 12, name: "Electromagnetic Induction", unit: "EMI & AC", audience: "neet" },
  { id: "phy-ac", subject: "physics", classLevel: 12, name: "Alternating Current", unit: "EMI & AC", audience: "neet" },
  { id: "phy-emwaves", subject: "physics", classLevel: 12, name: "Electromagnetic Waves", unit: "Optics & Modern", audience: "neet" },
  { id: "phy-ray", subject: "physics", classLevel: 12, name: "Ray Optics and Optical Instruments", unit: "Optics & Modern", audience: "neet" },
  { id: "phy-waveopt", subject: "physics", classLevel: 12, name: "Wave Optics", unit: "Optics & Modern", audience: "neet" },
  { id: "phy-dual", subject: "physics", classLevel: 12, name: "Dual Nature of Radiation and Matter", unit: "Optics & Modern", audience: "neet" },
  { id: "phy-atoms", subject: "physics", classLevel: 12, name: "Atoms", unit: "Optics & Modern", audience: "neet" },
  { id: "phy-nuclei", subject: "physics", classLevel: 12, name: "Nuclei", unit: "Optics & Modern", audience: "neet" },
  { id: "phy-semiconductor", subject: "physics", classLevel: 12, name: "Semiconductor Electronics", unit: "Optics & Modern", audience: "neet" },

  { id: "chem-basic", subject: "chemistry", classLevel: 11, name: "Some Basic Concepts of Chemistry", unit: "Physical", audience: "neet" },
  { id: "chem-atom", subject: "chemistry", classLevel: 11, name: "Structure of Atom", unit: "Physical", audience: "neet" },
  { id: "chem-periodic", subject: "chemistry", classLevel: 11, name: "Classification of Elements", unit: "Inorganic", audience: "neet" },
  { id: "chem-bonding", subject: "chemistry", classLevel: 11, name: "Chemical Bonding and Molecular Structure", unit: "Physical", audience: "neet" },
  { id: "chem-thermo", subject: "chemistry", classLevel: 11, name: "Chemical Thermodynamics", unit: "Physical", audience: "neet" },
  { id: "chem-eq", subject: "chemistry", classLevel: 11, name: "Equilibrium", unit: "Physical", audience: "neet" },
  { id: "chem-redox", subject: "chemistry", classLevel: 11, name: "Redox Reactions", unit: "Physical", audience: "neet" },
  { id: "chem-organic-basic", subject: "chemistry", classLevel: 11, name: "Organic Chemistry — Basic Principles", unit: "Organic", audience: "neet" },
  { id: "chem-hydrocarbons", subject: "chemistry", classLevel: 11, name: "Hydrocarbons", unit: "Organic", audience: "neet" },
  { id: "chem-solutions", subject: "chemistry", classLevel: 12, name: "Solutions", unit: "Physical", audience: "neet" },
  { id: "chem-electro", subject: "chemistry", classLevel: 12, name: "Electrochemistry", unit: "Physical", audience: "neet" },
  { id: "chem-kinetics", subject: "chemistry", classLevel: 12, name: "Chemical Kinetics", unit: "Physical", audience: "neet" },
  { id: "chem-dfblock", subject: "chemistry", classLevel: 12, name: "The d- and f-Block Elements", unit: "Inorganic", audience: "neet" },
  { id: "chem-coord", subject: "chemistry", classLevel: 12, name: "Coordination Compounds", unit: "Inorganic", audience: "neet" },
  { id: "chem-halo", subject: "chemistry", classLevel: 12, name: "Haloalkanes and Haloarenes", unit: "Organic", audience: "neet" },
  { id: "chem-alcohols", subject: "chemistry", classLevel: 12, name: "Alcohols, Phenols and Ethers", unit: "Organic", audience: "neet" },
  { id: "chem-carbonyl", subject: "chemistry", classLevel: 12, name: "Aldehydes, Ketones and Carboxylic Acids", unit: "Organic", audience: "neet" },
  { id: "chem-amines", subject: "chemistry", classLevel: 12, name: "Amines", unit: "Organic", audience: "neet" },
  { id: "chem-biomolecules", subject: "chemistry", classLevel: 12, name: "Biomolecules", unit: "Organic", audience: "neet" },

  { id: "bio-living", subject: "biology", classLevel: 11, name: "The Living World", unit: "Diversity", audience: "neet" },
  { id: "bio-classif", subject: "biology", classLevel: 11, name: "Biological Classification", unit: "Diversity", audience: "neet" },
  { id: "bio-plantk", subject: "biology", classLevel: 11, name: "Plant Kingdom", unit: "Diversity", audience: "neet" },
  { id: "bio-animalk", subject: "biology", classLevel: 11, name: "Animal Kingdom", unit: "Diversity", audience: "neet" },
  { id: "bio-morph", subject: "biology", classLevel: 11, name: "Morphology of Flowering Plants", unit: "Structural organisation", audience: "neet" },
  { id: "bio-anatomy", subject: "biology", classLevel: 11, name: "Anatomy of Flowering Plants", unit: "Structural organisation", audience: "neet" },
  { id: "bio-struct-anim", subject: "biology", classLevel: 11, name: "Structural Organisation in Animals", unit: "Structural organisation", audience: "neet" },
  { id: "bio-cell", subject: "biology", classLevel: 11, name: "Cell: The Unit of Life", unit: "Cell biology", audience: "neet" },
  { id: "bio-biomol", subject: "biology", classLevel: 11, name: "Biomolecules", unit: "Cell biology", audience: "neet" },
  { id: "bio-cellcycle", subject: "biology", classLevel: 11, name: "Cell Cycle and Cell Division", unit: "Cell biology", audience: "neet" },
  { id: "bio-photo", subject: "biology", classLevel: 11, name: "Photosynthesis in Higher Plants", unit: "Plant physiology", audience: "neet" },
  { id: "bio-resp", subject: "biology", classLevel: 11, name: "Respiration in Plants", unit: "Plant physiology", audience: "neet" },
  { id: "bio-growth", subject: "biology", classLevel: 11, name: "Plant Growth and Development", unit: "Plant physiology", audience: "neet" },
  { id: "bio-breathing", subject: "biology", classLevel: 11, name: "Breathing and Exchange of Gases", unit: "Human physiology", audience: "neet" },
  { id: "bio-circulation", subject: "biology", classLevel: 11, name: "Body Fluids and Circulation", unit: "Human physiology", audience: "neet" },
  { id: "bio-excretory", subject: "biology", classLevel: 11, name: "Excretory Products and their Elimination", unit: "Human physiology", audience: "neet" },
  { id: "bio-loco", subject: "biology", classLevel: 11, name: "Locomotion and Movement", unit: "Human physiology", audience: "neet" },
  { id: "bio-neural", subject: "biology", classLevel: 11, name: "Neural Control and Coordination", unit: "Human physiology", audience: "neet" },
  { id: "bio-endocrine", subject: "biology", classLevel: 11, name: "Chemical Coordination and Integration", unit: "Human physiology", audience: "neet" },
  { id: "bio-flower", subject: "biology", classLevel: 12, name: "Sexual Reproduction in Flowering Plants", unit: "Reproduction", audience: "neet" },
  { id: "bio-human-repro", subject: "biology", classLevel: 12, name: "Human Reproduction", unit: "Reproduction", audience: "neet" },
  { id: "bio-repro-health", subject: "biology", classLevel: 12, name: "Reproductive Health", unit: "Reproduction", audience: "neet" },
  { id: "bio-genetics", subject: "biology", classLevel: 12, name: "Principles of Inheritance and Variation", unit: "Genetics & evolution", audience: "neet" },
  { id: "bio-molecular", subject: "biology", classLevel: 12, name: "Molecular Basis of Inheritance", unit: "Genetics & evolution", audience: "neet" },
  { id: "bio-evolution", subject: "biology", classLevel: 12, name: "Evolution", unit: "Genetics & evolution", audience: "neet" },
  { id: "bio-health", subject: "biology", classLevel: 12, name: "Human Health and Disease", unit: "Biology in human welfare", audience: "neet" },
  { id: "bio-microbes", subject: "biology", classLevel: 12, name: "Microbes in Human Welfare", unit: "Biology in human welfare", audience: "neet" },
  { id: "bio-biotech-p", subject: "biology", classLevel: 12, name: "Biotechnology: Principles and Processes", unit: "Biotechnology", audience: "neet" },
  { id: "bio-biotech-a", subject: "biology", classLevel: 12, name: "Biotechnology and its Applications", unit: "Biotechnology", audience: "neet" },
  { id: "bio-organisms", subject: "biology", classLevel: 12, name: "Organisms and Populations", unit: "Ecology", audience: "neet" },
  { id: "bio-ecosystem", subject: "biology", classLevel: 12, name: "Ecosystem", unit: "Ecology", audience: "neet" },
  { id: "bio-biodiversity", subject: "biology", classLevel: 12, name: "Biodiversity and Conservation", unit: "Ecology", audience: "neet" },
];

export const SCHOOL_CHAPTERS: ChapterDef[] = [
  { id: "sch-matter", subject: "science", classLevel: 9, name: "Matter in Our Surroundings", unit: "Chemistry", audience: "school" },
  { id: "sch-atoms", subject: "science", classLevel: 9, name: "Atoms and Molecules", unit: "Chemistry", audience: "school" },
  { id: "sch-cells", subject: "science", classLevel: 9, name: "The Fundamental Unit of Life", unit: "Biology", audience: "school" },
  { id: "sch-tissues", subject: "science", classLevel: 9, name: "Tissues", unit: "Biology", audience: "school" },
  { id: "sch-motion", subject: "science", classLevel: 9, name: "Motion", unit: "Physics", audience: "school" },
  { id: "sch-force", subject: "science", classLevel: 9, name: "Force and Laws of Motion", unit: "Physics", audience: "school" },
  { id: "sch-gravitation", subject: "science", classLevel: 9, name: "Gravitation", unit: "Physics", audience: "school" },
  { id: "sch-work", subject: "science", classLevel: 9, name: "Work and Energy", unit: "Physics", audience: "school" },
  { id: "sch-sound", subject: "science", classLevel: 9, name: "Sound", unit: "Physics", audience: "school" },
  { id: "sch-life", subject: "science", classLevel: 10, name: "Life Processes", unit: "Biology", audience: "school" },
  { id: "sch-control", subject: "science", classLevel: 10, name: "Control and Coordination", unit: "Biology", audience: "school" },
  { id: "sch-repro", subject: "science", classLevel: 10, name: "How do Organisms Reproduce?", unit: "Biology", audience: "school" },
  { id: "sch-heredity", subject: "science", classLevel: 10, name: "Heredity", unit: "Biology", audience: "school" },
  { id: "sch-light", subject: "science", classLevel: 10, name: "Light — Reflection and Refraction", unit: "Physics", audience: "school" },
  { id: "sch-electricity", subject: "science", classLevel: 10, name: "Electricity", unit: "Physics", audience: "school" },
  { id: "sch-carbon", subject: "science", classLevel: 10, name: "Carbon and its Compounds", unit: "Chemistry", audience: "school" },
  { id: "sch-periodic", subject: "science", classLevel: 10, name: "Periodic Classification", unit: "Chemistry", audience: "school" },
  { id: "sch-metals", subject: "science", classLevel: 10, name: "Metals and Non-metals", unit: "Chemistry", audience: "school" },
  { id: "sch-env", subject: "science", classLevel: 10, name: "Our Environment", unit: "Biology", audience: "school" },
  { id: "sch-nresources", subject: "science", classLevel: 10, name: "Natural Resources & Management", unit: "Biology", audience: "school" },
];

export const ALL_CHAPTERS: ChapterDef[] = [...NEET_CHAPTERS, ...SCHOOL_CHAPTERS];

export function chapterById(id: string): ChapterDef | undefined {
  return ALL_CHAPTERS.find((c) => c.id === id);
}
